#ifdef ___LINKER_INFO
; File: "main.c", produced by Gambit-C v4.7.1
(
407001
" main"
((" main"))
(
"cr-lf"
"input"
"main"
"normal"
"output"
"repl"
"repl-pump"
"repl-service"
"stdin"
"stdout"
)
(
"direction"
"eol-encoding"
"intercept-output"
"permanent-close"
"reuse-address"
"server-address"
"test"
)
(
" main"
" main#0"
"*repl-intercept-output*"
"android-display"
"ide-repl-pump"
"main"
"make-ide-repl-ports"
"repl-channel-table"
"repl-server"
"repl-server-address"
"repl-server-initialize-defaults!"
"repl-server-start"
"setup-ide-repl-channel"
)
(
"##thread-make-repl-channel"
"c-scheme-main"
)
(
"##call-with-values"
"##default-thread-make-repl-channel"
"##make-repl-channel-ports"
"##repl-debug-main"
"##thread-interrupt!"
"##vector-set!"
"char=?"
"close-output-port"
"display"
"eof-object?"
"eq?"
"equal?"
"for-each"
"force-output"
"list"
"make-mutex"
"make-table"
"make-thread"
"make-thread-group"
"mutex-lock!"
"mutex-unlock!"
"not"
"open-string-pipe"
"open-tcp-server"
"read"
"read-char"
"read-line"
"string"
"table-ref"
"table-set!"
"thread-group->thread-list"
"thread-sleep!"
"thread-start!"
"thread-thread-group"
"values"
"void"
"with-exception-catcher"
"write-char"
)
 1
)
#else
#define ___VERSION 407001
#define ___MODULE_NAME " main"
#define ___LINKER_ID ____20_main
#define ___MH_PROC ___H__20_main
#define ___SCRIPT_LINE 0
#define ___SYMCOUNT 10
#define ___KEYCOUNT 7
#define ___GLOCOUNT 53
#define ___SUPCOUNT 15
#define ___CNSCOUNT 8
#define ___SUBCOUNT 7
#define ___LBLCOUNT 163
#define ___OFDCOUNT 4
#define ___MODDESCR ___REF_SUB(6)
#include "gambit.h"

___NEED_SYM(___S_cr_2d_lf)
___NEED_SYM(___S_input)
___NEED_SYM(___S_main)
___NEED_SYM(___S_normal)
___NEED_SYM(___S_output)
___NEED_SYM(___S_repl)
___NEED_SYM(___S_repl_2d_pump)
___NEED_SYM(___S_repl_2d_service)
___NEED_SYM(___S_stdin)
___NEED_SYM(___S_stdout)

___NEED_KEY(___K_direction)
___NEED_KEY(___K_eol_2d_encoding)
___NEED_KEY(___K_intercept_2d_output)
___NEED_KEY(___K_permanent_2d_close)
___NEED_KEY(___K_reuse_2d_address)
___NEED_KEY(___K_server_2d_address)
___NEED_KEY(___K_test)

___NEED_GLO(___G__20_main)
___NEED_GLO(___G__20_main_23_0)
___NEED_GLO(___G__23__23_call_2d_with_2d_values)
___NEED_GLO(___G__23__23_default_2d_thread_2d_make_2d_repl_2d_channel)
___NEED_GLO(___G__23__23_make_2d_repl_2d_channel_2d_ports)
___NEED_GLO(___G__23__23_repl_2d_debug_2d_main)
___NEED_GLO(___G__23__23_thread_2d_interrupt_21_)
___NEED_GLO(___G__23__23_thread_2d_make_2d_repl_2d_channel)
___NEED_GLO(___G__23__23_vector_2d_set_21_)
___NEED_GLO(___G__2a_repl_2d_intercept_2d_output_2a_)
___NEED_GLO(___G_android_2d_display)
___NEED_GLO(___G_c_2d_scheme_2d_main)
___NEED_GLO(___G_char_3d__3f_)
___NEED_GLO(___G_close_2d_output_2d_port)
___NEED_GLO(___G_display)
___NEED_GLO(___G_eof_2d_object_3f_)
___NEED_GLO(___G_eq_3f_)
___NEED_GLO(___G_equal_3f_)
___NEED_GLO(___G_for_2d_each)
___NEED_GLO(___G_force_2d_output)
___NEED_GLO(___G_ide_2d_repl_2d_pump)
___NEED_GLO(___G_list)
___NEED_GLO(___G_main)
___NEED_GLO(___G_make_2d_ide_2d_repl_2d_ports)
___NEED_GLO(___G_make_2d_mutex)
___NEED_GLO(___G_make_2d_table)
___NEED_GLO(___G_make_2d_thread)
___NEED_GLO(___G_make_2d_thread_2d_group)
___NEED_GLO(___G_mutex_2d_lock_21_)
___NEED_GLO(___G_mutex_2d_unlock_21_)
___NEED_GLO(___G_not)
___NEED_GLO(___G_open_2d_string_2d_pipe)
___NEED_GLO(___G_open_2d_tcp_2d_server)
___NEED_GLO(___G_read)
___NEED_GLO(___G_read_2d_char)
___NEED_GLO(___G_read_2d_line)
___NEED_GLO(___G_repl_2d_channel_2d_table)
___NEED_GLO(___G_repl_2d_server)
___NEED_GLO(___G_repl_2d_server_2d_address)
___NEED_GLO(___G_repl_2d_server_2d_initialize_2d_defaults_21_)
___NEED_GLO(___G_repl_2d_server_2d_start)
___NEED_GLO(___G_setup_2d_ide_2d_repl_2d_channel)
___NEED_GLO(___G_string)
___NEED_GLO(___G_table_2d_ref)
___NEED_GLO(___G_table_2d_set_21_)
___NEED_GLO(___G_thread_2d_group_2d__3e_thread_2d_list)
___NEED_GLO(___G_thread_2d_sleep_21_)
___NEED_GLO(___G_thread_2d_start_21_)
___NEED_GLO(___G_thread_2d_thread_2d_group)
___NEED_GLO(___G_values)
___NEED_GLO(___G_void)
___NEED_GLO(___G_with_2d_exception_2d_catcher)
___NEED_GLO(___G_write_2d_char)

___BEGIN_SYM
___DEF_SYM(0,___S_cr_2d_lf,"cr-lf")
___DEF_SYM(1,___S_input,"input")
___DEF_SYM(2,___S_main,"main")
___DEF_SYM(3,___S_normal,"normal")
___DEF_SYM(4,___S_output,"output")
___DEF_SYM(5,___S_repl,"repl")
___DEF_SYM(6,___S_repl_2d_pump,"repl-pump")
___DEF_SYM(7,___S_repl_2d_service,"repl-service")
___DEF_SYM(8,___S_stdin,"stdin")
___DEF_SYM(9,___S_stdout,"stdout")
___END_SYM

#define ___SYM_cr_2d_lf ___SYM(0,___S_cr_2d_lf)
#define ___SYM_input ___SYM(1,___S_input)
#define ___SYM_main ___SYM(2,___S_main)
#define ___SYM_normal ___SYM(3,___S_normal)
#define ___SYM_output ___SYM(4,___S_output)
#define ___SYM_repl ___SYM(5,___S_repl)
#define ___SYM_repl_2d_pump ___SYM(6,___S_repl_2d_pump)
#define ___SYM_repl_2d_service ___SYM(7,___S_repl_2d_service)
#define ___SYM_stdin ___SYM(8,___S_stdin)
#define ___SYM_stdout ___SYM(9,___S_stdout)

___BEGIN_KEY
___DEF_KEY(0,___K_direction,"direction")
___DEF_KEY(1,___K_eol_2d_encoding,"eol-encoding")
___DEF_KEY(2,___K_intercept_2d_output,"intercept-output")
___DEF_KEY(3,___K_permanent_2d_close,"permanent-close")
___DEF_KEY(4,___K_reuse_2d_address,"reuse-address")
___DEF_KEY(5,___K_server_2d_address,"server-address")
___DEF_KEY(6,___K_test,"test")
___END_KEY

#define ___KEY_direction ___KEY(0,___K_direction)
#define ___KEY_eol_2d_encoding ___KEY(1,___K_eol_2d_encoding)
#define ___KEY_intercept_2d_output ___KEY(2,___K_intercept_2d_output)
#define ___KEY_permanent_2d_close ___KEY(3,___K_permanent_2d_close)
#define ___KEY_reuse_2d_address ___KEY(4,___K_reuse_2d_address)
#define ___KEY_server_2d_address ___KEY(5,___K_server_2d_address)
#define ___KEY_test ___KEY(6,___K_test)

___BEGIN_GLO
___DEF_GLO(0," main")
___DEF_GLO(1," main#0")
___DEF_GLO(2,"##thread-make-repl-channel")
___DEF_GLO(3,"*repl-intercept-output*")
___DEF_GLO(4,"android-display")
___DEF_GLO(5,"c-scheme-main")
___DEF_GLO(6,"ide-repl-pump")
___DEF_GLO(7,"main")
___DEF_GLO(8,"make-ide-repl-ports")
___DEF_GLO(9,"repl-channel-table")
___DEF_GLO(10,"repl-server")
___DEF_GLO(11,"repl-server-address")
___DEF_GLO(12,"repl-server-initialize-defaults!")
___DEF_GLO(13,"repl-server-start")
___DEF_GLO(14,"setup-ide-repl-channel")
___DEF_GLO(15,"##call-with-values")
___DEF_GLO(16,"##default-thread-make-repl-channel")

___DEF_GLO(17,"##make-repl-channel-ports")
___DEF_GLO(18,"##repl-debug-main")
___DEF_GLO(19,"##thread-interrupt!")
___DEF_GLO(20,"##vector-set!")
___DEF_GLO(21,"char=?")
___DEF_GLO(22,"close-output-port")
___DEF_GLO(23,"display")
___DEF_GLO(24,"eof-object?")
___DEF_GLO(25,"eq?")
___DEF_GLO(26,"equal?")
___DEF_GLO(27,"for-each")
___DEF_GLO(28,"force-output")
___DEF_GLO(29,"list")
___DEF_GLO(30,"make-mutex")
___DEF_GLO(31,"make-table")
___DEF_GLO(32,"make-thread")
___DEF_GLO(33,"make-thread-group")
___DEF_GLO(34,"mutex-lock!")
___DEF_GLO(35,"mutex-unlock!")
___DEF_GLO(36,"not")
___DEF_GLO(37,"open-string-pipe")
___DEF_GLO(38,"open-tcp-server")
___DEF_GLO(39,"read")
___DEF_GLO(40,"read-char")
___DEF_GLO(41,"read-line")
___DEF_GLO(42,"string")
___DEF_GLO(43,"table-ref")
___DEF_GLO(44,"table-set!")
___DEF_GLO(45,"thread-group->thread-list")
___DEF_GLO(46,"thread-sleep!")
___DEF_GLO(47,"thread-start!")
___DEF_GLO(48,"thread-thread-group")
___DEF_GLO(49,"values")
___DEF_GLO(50,"void")
___DEF_GLO(51,"with-exception-catcher")
___DEF_GLO(52,"write-char")
___END_GLO

#define ___GLO__20_main ___GLO(0,___G__20_main)
#define ___PRM__20_main ___PRM(0,___G__20_main)
#define ___GLO__20_main_23_0 ___GLO(1,___G__20_main_23_0)
#define ___PRM__20_main_23_0 ___PRM(1,___G__20_main_23_0)
#define ___GLO__23__23_thread_2d_make_2d_repl_2d_channel ___GLO(2,___G__23__23_thread_2d_make_2d_repl_2d_channel)
#define ___PRM__23__23_thread_2d_make_2d_repl_2d_channel ___PRM(2,___G__23__23_thread_2d_make_2d_repl_2d_channel)
#define ___GLO__2a_repl_2d_intercept_2d_output_2a_ ___GLO(3,___G__2a_repl_2d_intercept_2d_output_2a_)
#define ___PRM__2a_repl_2d_intercept_2d_output_2a_ ___PRM(3,___G__2a_repl_2d_intercept_2d_output_2a_)
#define ___GLO_android_2d_display ___GLO(4,___G_android_2d_display)
#define ___PRM_android_2d_display ___PRM(4,___G_android_2d_display)
#define ___GLO_c_2d_scheme_2d_main ___GLO(5,___G_c_2d_scheme_2d_main)
#define ___PRM_c_2d_scheme_2d_main ___PRM(5,___G_c_2d_scheme_2d_main)
#define ___GLO_ide_2d_repl_2d_pump ___GLO(6,___G_ide_2d_repl_2d_pump)
#define ___PRM_ide_2d_repl_2d_pump ___PRM(6,___G_ide_2d_repl_2d_pump)
#define ___GLO_main ___GLO(7,___G_main)
#define ___PRM_main ___PRM(7,___G_main)
#define ___GLO_make_2d_ide_2d_repl_2d_ports ___GLO(8,___G_make_2d_ide_2d_repl_2d_ports)
#define ___PRM_make_2d_ide_2d_repl_2d_ports ___PRM(8,___G_make_2d_ide_2d_repl_2d_ports)
#define ___GLO_repl_2d_channel_2d_table ___GLO(9,___G_repl_2d_channel_2d_table)
#define ___PRM_repl_2d_channel_2d_table ___PRM(9,___G_repl_2d_channel_2d_table)
#define ___GLO_repl_2d_server ___GLO(10,___G_repl_2d_server)
#define ___PRM_repl_2d_server ___PRM(10,___G_repl_2d_server)
#define ___GLO_repl_2d_server_2d_address ___GLO(11,___G_repl_2d_server_2d_address)
#define ___PRM_repl_2d_server_2d_address ___PRM(11,___G_repl_2d_server_2d_address)
#define ___GLO_repl_2d_server_2d_initialize_2d_defaults_21_ ___GLO(12,___G_repl_2d_server_2d_initialize_2d_defaults_21_)
#define ___PRM_repl_2d_server_2d_initialize_2d_defaults_21_ ___PRM(12,___G_repl_2d_server_2d_initialize_2d_defaults_21_)
#define ___GLO_repl_2d_server_2d_start ___GLO(13,___G_repl_2d_server_2d_start)
#define ___PRM_repl_2d_server_2d_start ___PRM(13,___G_repl_2d_server_2d_start)
#define ___GLO_setup_2d_ide_2d_repl_2d_channel ___GLO(14,___G_setup_2d_ide_2d_repl_2d_channel)
#define ___PRM_setup_2d_ide_2d_repl_2d_channel ___PRM(14,___G_setup_2d_ide_2d_repl_2d_channel)
#define ___GLO__23__23_call_2d_with_2d_values ___GLO(15,___G__23__23_call_2d_with_2d_values)
#define ___PRM__23__23_call_2d_with_2d_values ___PRM(15,___G__23__23_call_2d_with_2d_values)
#define ___GLO__23__23_default_2d_thread_2d_make_2d_repl_2d_channel ___GLO(16,___G__23__23_default_2d_thread_2d_make_2d_repl_2d_channel)
#define ___PRM__23__23_default_2d_thread_2d_make_2d_repl_2d_channel ___PRM(16,___G__23__23_default_2d_thread_2d_make_2d_repl_2d_channel)
#define ___GLO__23__23_make_2d_repl_2d_channel_2d_ports ___GLO(17,___G__23__23_make_2d_repl_2d_channel_2d_ports)
#define ___PRM__23__23_make_2d_repl_2d_channel_2d_ports ___PRM(17,___G__23__23_make_2d_repl_2d_channel_2d_ports)
#define ___GLO__23__23_repl_2d_debug_2d_main ___GLO(18,___G__23__23_repl_2d_debug_2d_main)
#define ___PRM__23__23_repl_2d_debug_2d_main ___PRM(18,___G__23__23_repl_2d_debug_2d_main)
#define ___GLO__23__23_thread_2d_interrupt_21_ ___GLO(19,___G__23__23_thread_2d_interrupt_21_)
#define ___PRM__23__23_thread_2d_interrupt_21_ ___PRM(19,___G__23__23_thread_2d_interrupt_21_)
#define ___GLO__23__23_vector_2d_set_21_ ___GLO(20,___G__23__23_vector_2d_set_21_)
#define ___PRM__23__23_vector_2d_set_21_ ___PRM(20,___G__23__23_vector_2d_set_21_)
#define ___GLO_char_3d__3f_ ___GLO(21,___G_char_3d__3f_)
#define ___PRM_char_3d__3f_ ___PRM(21,___G_char_3d__3f_)
#define ___GLO_close_2d_output_2d_port ___GLO(22,___G_close_2d_output_2d_port)
#define ___PRM_close_2d_output_2d_port ___PRM(22,___G_close_2d_output_2d_port)
#define ___GLO_display ___GLO(23,___G_display)
#define ___PRM_display ___PRM(23,___G_display)
#define ___GLO_eof_2d_object_3f_ ___GLO(24,___G_eof_2d_object_3f_)
#define ___PRM_eof_2d_object_3f_ ___PRM(24,___G_eof_2d_object_3f_)
#define ___GLO_eq_3f_ ___GLO(25,___G_eq_3f_)
#define ___PRM_eq_3f_ ___PRM(25,___G_eq_3f_)
#define ___GLO_equal_3f_ ___GLO(26,___G_equal_3f_)
#define ___PRM_equal_3f_ ___PRM(26,___G_equal_3f_)
#define ___GLO_for_2d_each ___GLO(27,___G_for_2d_each)
#define ___PRM_for_2d_each ___PRM(27,___G_for_2d_each)
#define ___GLO_force_2d_output ___GLO(28,___G_force_2d_output)
#define ___PRM_force_2d_output ___PRM(28,___G_force_2d_output)
#define ___GLO_list ___GLO(29,___G_list)
#define ___PRM_list ___PRM(29,___G_list)
#define ___GLO_make_2d_mutex ___GLO(30,___G_make_2d_mutex)
#define ___PRM_make_2d_mutex ___PRM(30,___G_make_2d_mutex)
#define ___GLO_make_2d_table ___GLO(31,___G_make_2d_table)
#define ___PRM_make_2d_table ___PRM(31,___G_make_2d_table)
#define ___GLO_make_2d_thread ___GLO(32,___G_make_2d_thread)
#define ___PRM_make_2d_thread ___PRM(32,___G_make_2d_thread)
#define ___GLO_make_2d_thread_2d_group ___GLO(33,___G_make_2d_thread_2d_group)
#define ___PRM_make_2d_thread_2d_group ___PRM(33,___G_make_2d_thread_2d_group)
#define ___GLO_mutex_2d_lock_21_ ___GLO(34,___G_mutex_2d_lock_21_)
#define ___PRM_mutex_2d_lock_21_ ___PRM(34,___G_mutex_2d_lock_21_)
#define ___GLO_mutex_2d_unlock_21_ ___GLO(35,___G_mutex_2d_unlock_21_)
#define ___PRM_mutex_2d_unlock_21_ ___PRM(35,___G_mutex_2d_unlock_21_)
#define ___GLO_not ___GLO(36,___G_not)
#define ___PRM_not ___PRM(36,___G_not)
#define ___GLO_open_2d_string_2d_pipe ___GLO(37,___G_open_2d_string_2d_pipe)
#define ___PRM_open_2d_string_2d_pipe ___PRM(37,___G_open_2d_string_2d_pipe)
#define ___GLO_open_2d_tcp_2d_server ___GLO(38,___G_open_2d_tcp_2d_server)
#define ___PRM_open_2d_tcp_2d_server ___PRM(38,___G_open_2d_tcp_2d_server)
#define ___GLO_read ___GLO(39,___G_read)
#define ___PRM_read ___PRM(39,___G_read)
#define ___GLO_read_2d_char ___GLO(40,___G_read_2d_char)
#define ___PRM_read_2d_char ___PRM(40,___G_read_2d_char)
#define ___GLO_read_2d_line ___GLO(41,___G_read_2d_line)
#define ___PRM_read_2d_line ___PRM(41,___G_read_2d_line)
#define ___GLO_string ___GLO(42,___G_string)
#define ___PRM_string ___PRM(42,___G_string)
#define ___GLO_table_2d_ref ___GLO(43,___G_table_2d_ref)
#define ___PRM_table_2d_ref ___PRM(43,___G_table_2d_ref)
#define ___GLO_table_2d_set_21_ ___GLO(44,___G_table_2d_set_21_)
#define ___PRM_table_2d_set_21_ ___PRM(44,___G_table_2d_set_21_)
#define ___GLO_thread_2d_group_2d__3e_thread_2d_list ___GLO(45,___G_thread_2d_group_2d__3e_thread_2d_list)
#define ___PRM_thread_2d_group_2d__3e_thread_2d_list ___PRM(45,___G_thread_2d_group_2d__3e_thread_2d_list)
#define ___GLO_thread_2d_sleep_21_ ___GLO(46,___G_thread_2d_sleep_21_)
#define ___PRM_thread_2d_sleep_21_ ___PRM(46,___G_thread_2d_sleep_21_)
#define ___GLO_thread_2d_start_21_ ___GLO(47,___G_thread_2d_start_21_)
#define ___PRM_thread_2d_start_21_ ___PRM(47,___G_thread_2d_start_21_)
#define ___GLO_thread_2d_thread_2d_group ___GLO(48,___G_thread_2d_thread_2d_group)
#define ___PRM_thread_2d_thread_2d_group ___PRM(48,___G_thread_2d_thread_2d_group)
#define ___GLO_values ___GLO(49,___G_values)
#define ___PRM_values ___PRM(49,___G_values)
#define ___GLO_void ___GLO(50,___G_void)
#define ___PRM_void ___PRM(50,___G_void)
#define ___GLO_with_2d_exception_2d_catcher ___GLO(51,___G_with_2d_exception_2d_catcher)
#define ___PRM_with_2d_exception_2d_catcher ___PRM(51,___G_with_2d_exception_2d_catcher)
#define ___GLO_write_2d_char ___GLO(52,___G_write_2d_char)
#define ___PRM_write_2d_char ___PRM(52,___G_write_2d_char)

___BEGIN_CNS
 ___DEF_CNS(___REF_SYM(9,___S_stdout),___REF_NUL)
,___DEF_CNS(___REF_SYM(8,___S_stdin),___REF_NUL)
,___DEF_CNS(___REF_KEY(0,___K_direction),___REF_CNS(3))
,___DEF_CNS(___REF_SYM(4,___S_output),___REF_NUL)
,___DEF_CNS(___REF_KEY(0,___K_direction),___REF_CNS(5))
,___DEF_CNS(___REF_SYM(1,___S_input),___REF_CNS(6))
,___DEF_CNS(___REF_KEY(3,___K_permanent_2d_close),___REF_CNS(7))
,___DEF_CNS(___REF_FAL,___REF_NUL)
___END_CNS

___DEF_SUB_STR(___X0,17)
               ___STR8(67,108,105,101,110,116,32,67)
               ___STR8(111,110,110,101,99,116,101,100)
               ___STR1(10)
___DEF_SUB_STR(___X1,10)
               ___STR8(80,97,115,115,119,111,114,100)
               ___STR2(58,32)
___DEF_SUB_VEC(___X2,2)
               ___VEC1(___REF_KEY(2,___K_intercept_2d_output))
               ___VEC1(___REF_FAL)
               ___VEC0
___DEF_SUB_STR(___X3,6)
               ___STR6(42,58,55,48,48,48)
___DEF_SUB_STR(___X4,4)
               ___STR4(97,115,100,102)
___DEF_SUB_FLO(___X5,0x7ff00000L,0x0L)
___DEF_SUB_VEC(___X6,5)
               ___VEC1(___REF_SYM(2,___S_main))
               ___VEC1(___REF_PRC(1))
               ___VEC1(___REF_FIX(1))
               ___VEC1(___REF_NUL)
               ___VEC1(___REF_FAL)
               ___VEC0

___BEGIN_SUB
 ___DEF_SUB(___X0)
,___DEF_SUB(___X1)
,___DEF_SUB(___X2)
,___DEF_SUB(___X3)
,___DEF_SUB(___X4)
,___DEF_SUB(___X5)
,___DEF_SUB(___X6)
___END_SUB


#define ___C_LBL_scheme_main 161

 void scheme_main ___PVOID
{
#define ___NARGS 0
___BEGIN_SFUN_VOID(___MLBL(___C_LBL_scheme_main))
___BEGIN_SFUN_BODY
___SFUN_CALL_VOID
___SFUN_SET_RESULT_VOID
___END_SFUN_BODY
___SFUN_ERROR_VOID
___SFUN_SET_RESULT_VOID
___END_SFUN_VOID
#undef ___NARGS
}


#undef ___MD_ALL
#define ___MD_ALL ___D_HEAP ___D_FP ___D_R0 ___D_R1 ___D_R2 ___D_R3 ___D_R4
#undef ___MR_ALL
#define ___MR_ALL ___R_HEAP ___R_FP ___R_R0 ___R_R1 ___R_R2 ___R_R3 ___R_R4
#undef ___MW_ALL
#define ___MW_ALL ___W_HEAP ___W_FP ___W_R0 ___W_R1 ___W_R2 ___W_R3 ___W_R4
___BEGIN_M_COD
___BEGIN_M_HLBL
___DEF_M_HLBL_INTRO
___DEF_M_HLBL(___L0__20_main)
___DEF_M_HLBL(___L1__20_main)
___DEF_M_HLBL(___L2__20_main)
___DEF_M_HLBL(___L3__20_main)
___DEF_M_HLBL_INTRO
___DEF_M_HLBL(___L0__20_main_23_0)
___DEF_M_HLBL(___L1__20_main_23_0)
___DEF_M_HLBL_INTRO
___DEF_M_HLBL(___L0__2a_repl_2d_intercept_2d_output_2a_)
___DEF_M_HLBL(___L1__2a_repl_2d_intercept_2d_output_2a_)
___DEF_M_HLBL_INTRO
___DEF_M_HLBL(___L0_ide_2d_repl_2d_pump)
___DEF_M_HLBL(___L1_ide_2d_repl_2d_pump)
___DEF_M_HLBL(___L2_ide_2d_repl_2d_pump)
___DEF_M_HLBL(___L3_ide_2d_repl_2d_pump)
___DEF_M_HLBL(___L4_ide_2d_repl_2d_pump)
___DEF_M_HLBL(___L5_ide_2d_repl_2d_pump)
___DEF_M_HLBL(___L6_ide_2d_repl_2d_pump)
___DEF_M_HLBL(___L7_ide_2d_repl_2d_pump)
___DEF_M_HLBL(___L8_ide_2d_repl_2d_pump)
___DEF_M_HLBL(___L9_ide_2d_repl_2d_pump)
___DEF_M_HLBL(___L10_ide_2d_repl_2d_pump)
___DEF_M_HLBL(___L11_ide_2d_repl_2d_pump)
___DEF_M_HLBL(___L12_ide_2d_repl_2d_pump)
___DEF_M_HLBL(___L13_ide_2d_repl_2d_pump)
___DEF_M_HLBL(___L14_ide_2d_repl_2d_pump)
___DEF_M_HLBL(___L15_ide_2d_repl_2d_pump)
___DEF_M_HLBL(___L16_ide_2d_repl_2d_pump)
___DEF_M_HLBL(___L17_ide_2d_repl_2d_pump)
___DEF_M_HLBL(___L18_ide_2d_repl_2d_pump)
___DEF_M_HLBL(___L19_ide_2d_repl_2d_pump)
___DEF_M_HLBL(___L20_ide_2d_repl_2d_pump)
___DEF_M_HLBL(___L21_ide_2d_repl_2d_pump)
___DEF_M_HLBL(___L22_ide_2d_repl_2d_pump)
___DEF_M_HLBL(___L23_ide_2d_repl_2d_pump)
___DEF_M_HLBL(___L24_ide_2d_repl_2d_pump)
___DEF_M_HLBL(___L25_ide_2d_repl_2d_pump)
___DEF_M_HLBL(___L26_ide_2d_repl_2d_pump)
___DEF_M_HLBL(___L27_ide_2d_repl_2d_pump)
___DEF_M_HLBL(___L28_ide_2d_repl_2d_pump)
___DEF_M_HLBL(___L29_ide_2d_repl_2d_pump)
___DEF_M_HLBL(___L30_ide_2d_repl_2d_pump)
___DEF_M_HLBL(___L31_ide_2d_repl_2d_pump)
___DEF_M_HLBL(___L32_ide_2d_repl_2d_pump)
___DEF_M_HLBL(___L33_ide_2d_repl_2d_pump)
___DEF_M_HLBL(___L34_ide_2d_repl_2d_pump)
___DEF_M_HLBL(___L35_ide_2d_repl_2d_pump)
___DEF_M_HLBL(___L36_ide_2d_repl_2d_pump)
___DEF_M_HLBL(___L37_ide_2d_repl_2d_pump)
___DEF_M_HLBL(___L38_ide_2d_repl_2d_pump)
___DEF_M_HLBL(___L39_ide_2d_repl_2d_pump)
___DEF_M_HLBL(___L40_ide_2d_repl_2d_pump)
___DEF_M_HLBL(___L41_ide_2d_repl_2d_pump)
___DEF_M_HLBL(___L42_ide_2d_repl_2d_pump)
___DEF_M_HLBL(___L43_ide_2d_repl_2d_pump)
___DEF_M_HLBL(___L44_ide_2d_repl_2d_pump)
___DEF_M_HLBL(___L45_ide_2d_repl_2d_pump)
___DEF_M_HLBL(___L46_ide_2d_repl_2d_pump)
___DEF_M_HLBL(___L47_ide_2d_repl_2d_pump)
___DEF_M_HLBL(___L48_ide_2d_repl_2d_pump)
___DEF_M_HLBL(___L49_ide_2d_repl_2d_pump)
___DEF_M_HLBL(___L50_ide_2d_repl_2d_pump)
___DEF_M_HLBL(___L51_ide_2d_repl_2d_pump)
___DEF_M_HLBL(___L52_ide_2d_repl_2d_pump)
___DEF_M_HLBL(___L53_ide_2d_repl_2d_pump)
___DEF_M_HLBL(___L54_ide_2d_repl_2d_pump)
___DEF_M_HLBL(___L55_ide_2d_repl_2d_pump)
___DEF_M_HLBL(___L56_ide_2d_repl_2d_pump)
___DEF_M_HLBL(___L57_ide_2d_repl_2d_pump)
___DEF_M_HLBL(___L58_ide_2d_repl_2d_pump)
___DEF_M_HLBL(___L59_ide_2d_repl_2d_pump)
___DEF_M_HLBL_INTRO
___DEF_M_HLBL(___L0_make_2d_ide_2d_repl_2d_ports)
___DEF_M_HLBL(___L1_make_2d_ide_2d_repl_2d_ports)
___DEF_M_HLBL(___L2_make_2d_ide_2d_repl_2d_ports)
___DEF_M_HLBL(___L3_make_2d_ide_2d_repl_2d_ports)
___DEF_M_HLBL(___L4_make_2d_ide_2d_repl_2d_ports)
___DEF_M_HLBL(___L5_make_2d_ide_2d_repl_2d_ports)
___DEF_M_HLBL(___L6_make_2d_ide_2d_repl_2d_ports)
___DEF_M_HLBL(___L7_make_2d_ide_2d_repl_2d_ports)
___DEF_M_HLBL(___L8_make_2d_ide_2d_repl_2d_ports)
___DEF_M_HLBL(___L9_make_2d_ide_2d_repl_2d_ports)
___DEF_M_HLBL(___L10_make_2d_ide_2d_repl_2d_ports)
___DEF_M_HLBL(___L11_make_2d_ide_2d_repl_2d_ports)
___DEF_M_HLBL(___L12_make_2d_ide_2d_repl_2d_ports)
___DEF_M_HLBL(___L13_make_2d_ide_2d_repl_2d_ports)
___DEF_M_HLBL(___L14_make_2d_ide_2d_repl_2d_ports)
___DEF_M_HLBL(___L15_make_2d_ide_2d_repl_2d_ports)
___DEF_M_HLBL(___L16_make_2d_ide_2d_repl_2d_ports)
___DEF_M_HLBL(___L17_make_2d_ide_2d_repl_2d_ports)
___DEF_M_HLBL(___L18_make_2d_ide_2d_repl_2d_ports)
___DEF_M_HLBL(___L19_make_2d_ide_2d_repl_2d_ports)
___DEF_M_HLBL_INTRO
___DEF_M_HLBL(___L0_setup_2d_ide_2d_repl_2d_channel)
___DEF_M_HLBL(___L1_setup_2d_ide_2d_repl_2d_channel)
___DEF_M_HLBL(___L2_setup_2d_ide_2d_repl_2d_channel)
___DEF_M_HLBL(___L3_setup_2d_ide_2d_repl_2d_channel)
___DEF_M_HLBL(___L4_setup_2d_ide_2d_repl_2d_channel)
___DEF_M_HLBL(___L5_setup_2d_ide_2d_repl_2d_channel)
___DEF_M_HLBL(___L6_setup_2d_ide_2d_repl_2d_channel)
___DEF_M_HLBL(___L7_setup_2d_ide_2d_repl_2d_channel)
___DEF_M_HLBL(___L8_setup_2d_ide_2d_repl_2d_channel)
___DEF_M_HLBL_INTRO
___DEF_M_HLBL(___L0_repl_2d_server)
___DEF_M_HLBL(___L1_repl_2d_server)
___DEF_M_HLBL(___L2_repl_2d_server)
___DEF_M_HLBL(___L3_repl_2d_server)
___DEF_M_HLBL(___L4_repl_2d_server)
___DEF_M_HLBL(___L5_repl_2d_server)
___DEF_M_HLBL(___L6_repl_2d_server)
___DEF_M_HLBL(___L7_repl_2d_server)
___DEF_M_HLBL(___L8_repl_2d_server)
___DEF_M_HLBL(___L9_repl_2d_server)
___DEF_M_HLBL(___L10_repl_2d_server)
___DEF_M_HLBL(___L11_repl_2d_server)
___DEF_M_HLBL(___L12_repl_2d_server)
___DEF_M_HLBL(___L13_repl_2d_server)
___DEF_M_HLBL(___L14_repl_2d_server)
___DEF_M_HLBL(___L15_repl_2d_server)
___DEF_M_HLBL(___L16_repl_2d_server)
___DEF_M_HLBL(___L17_repl_2d_server)
___DEF_M_HLBL(___L18_repl_2d_server)
___DEF_M_HLBL(___L19_repl_2d_server)
___DEF_M_HLBL(___L20_repl_2d_server)
___DEF_M_HLBL(___L21_repl_2d_server)
___DEF_M_HLBL(___L22_repl_2d_server)
___DEF_M_HLBL(___L23_repl_2d_server)
___DEF_M_HLBL(___L24_repl_2d_server)
___DEF_M_HLBL(___L25_repl_2d_server)
___DEF_M_HLBL(___L26_repl_2d_server)
___DEF_M_HLBL(___L27_repl_2d_server)
___DEF_M_HLBL_INTRO
___DEF_M_HLBL(___L0_repl_2d_server_2d_start)
___DEF_M_HLBL(___L1_repl_2d_server_2d_start)
___DEF_M_HLBL(___L2_repl_2d_server_2d_start)
___DEF_M_HLBL(___L3_repl_2d_server_2d_start)
___DEF_M_HLBL(___L4_repl_2d_server_2d_start)
___DEF_M_HLBL(___L5_repl_2d_server_2d_start)
___DEF_M_HLBL(___L6_repl_2d_server_2d_start)
___DEF_M_HLBL(___L7_repl_2d_server_2d_start)
___DEF_M_HLBL(___L8_repl_2d_server_2d_start)
___DEF_M_HLBL_INTRO
___DEF_M_HLBL(___L0_repl_2d_server_2d_initialize_2d_defaults_21_)
___DEF_M_HLBL(___L1_repl_2d_server_2d_initialize_2d_defaults_21_)
___DEF_M_HLBL(___L2_repl_2d_server_2d_initialize_2d_defaults_21_)
___DEF_M_HLBL(___L3_repl_2d_server_2d_initialize_2d_defaults_21_)
___DEF_M_HLBL(___L4_repl_2d_server_2d_initialize_2d_defaults_21_)
___DEF_M_HLBL(___L5_repl_2d_server_2d_initialize_2d_defaults_21_)
___DEF_M_HLBL(___L6_repl_2d_server_2d_initialize_2d_defaults_21_)
___DEF_M_HLBL_INTRO
___DEF_M_HLBL(___L0_main)
___DEF_M_HLBL(___L1_main)
___DEF_M_HLBL(___L2_main)
___DEF_M_HLBL(___L3_main)
___DEF_M_HLBL(___L4_main)
___DEF_M_HLBL(___L5_main)
___DEF_M_HLBL(___L6_main)
___DEF_M_HLBL(___L7_main)
___DEF_M_HLBL(___L8_main)
___DEF_M_HLBL_INTRO
___DEF_M_HLBL(___L0_c_2d_scheme_2d_main)
___DEF_M_HLBL(___L1_c_2d_scheme_2d_main)
___END_M_HLBL

___BEGIN_M_SW

#undef ___PH_PROC
#define ___PH_PROC ___H__20_main
#undef ___PH_LBL0
#define ___PH_LBL0 1
#undef ___PD_ALL
#define ___PD_ALL ___D_FP ___D_R0 ___D_R1 ___D_R2 ___D_R4
#undef ___PR_ALL
#define ___PR_ALL ___R_FP ___R_R0 ___R_R1 ___R_R2 ___R_R4
#undef ___PW_ALL
#define ___PW_ALL ___W_FP ___W_R0 ___W_R1 ___W_R2 ___W_R4
___BEGIN_P_COD
___BEGIN_P_HLBL
___DEF_P_HLBL_INTRO
___DEF_P_HLBL(___L0__20_main)
___DEF_P_HLBL(___L1__20_main)
___DEF_P_HLBL(___L2__20_main)
___DEF_P_HLBL(___L3__20_main)
___END_P_HLBL
___BEGIN_P_SW
___DEF_SLBL(0,___L0__20_main)
   ___IF_NARGS_EQ(0,___NOTHING)
   ___WRONG_NARGS(0,0,0,0)
___DEF_GLBL(___L__20_main)
   ___SET_GLO(4,___G_android_2d_display,___PRC(6))
   ___SET_GLO(3,___G__2a_repl_2d_intercept_2d_output_2a_,___PRC(9))
   ___SET_GLO(6,___G_ide_2d_repl_2d_pump,___PRC(12))
   ___SET_GLO(8,___G_make_2d_ide_2d_repl_2d_ports,___PRC(73))
   ___SET_STK(1,___R0)
   ___SET_R2(___GLO_eq_3f_)
   ___SET_R1(___KEY_test)
   ___SET_R0(___LBL(2))
   ___ADJFP(4)
   ___POLL(1)
___DEF_SLBL(1,___L1__20_main)
   ___JUMPGLOSAFE(___SET_NARGS(2),31,___G_make_2d_table)
___DEF_SLBL(2,___L2__20_main)
   ___SET_GLO(9,___G_repl_2d_channel_2d_table,___R1)
   ___SET_GLO(14,___G_setup_2d_ide_2d_repl_2d_channel,___PRC(94))
   ___SET_GLO(11,___G_repl_2d_server_2d_address,___FAL)
   ___SET_GLO(10,___G_repl_2d_server,___PRC(104))
   ___SET_GLO(13,___G_repl_2d_server_2d_start,___PRC(133))
   ___SET_GLO(12,___G_repl_2d_server_2d_initialize_2d_defaults_21_,___PRC(143))
   ___SET_GLO(7,___G_main,___PRC(151))
   ___SET_GLO(5,___G_c_2d_scheme_2d_main,___PRC(161))
   ___SET_R1(___VOID)
   ___POLL(3)
___DEF_SLBL(3,___L3__20_main)
   ___ADJFP(-4)
   ___JUMPPRM(___NOTHING,___STK(1))
___END_P_SW
___END_P_COD

#undef ___PH_PROC
#define ___PH_PROC ___H__20_main_23_0
#undef ___PH_LBL0
#define ___PH_LBL0 6
#undef ___PD_ALL
#define ___PD_ALL ___D_FP ___D_R0 ___D_R1
#undef ___PR_ALL
#define ___PR_ALL ___R_FP ___R_R0 ___R_R1
#undef ___PW_ALL
#define ___PW_ALL ___W_FP ___W_R0
___BEGIN_P_COD
___BEGIN_P_HLBL
___DEF_P_HLBL_INTRO
___DEF_P_HLBL(___L0__20_main_23_0)
___DEF_P_HLBL(___L1__20_main_23_0)
___END_P_HLBL
___BEGIN_P_SW
___DEF_SLBL(0,___L0__20_main_23_0)
   ___IF_NARGS_EQ(1,___NOTHING)
   ___WRONG_NARGS(0,1,0,0)
___DEF_GLBL(___L__20_main_23_0)
   ___SET_STK(1,___R1)
   ___SET_STK(2,___R0)
   ___SET_R0(___LBL(1))
   ___ADJFP(8)
#define ___NARGS 1
___BEGIN_CFUN_VOID
#define ___ARG1 ___CFUN_ARG(1)
___BEGIN_CFUN_ARG(1,char* ___arg1)
___BEGIN_CFUN_SCMOBJ_TO_CHARSTRING(___ARG1,___arg1,1)
___BEGIN_CFUN_BODY_CLEANUP
#undef ___AT_END
___CFUN_CALL_VOID(input_from_scheme(___arg1))
#ifndef ___AT_END
#define ___AT_END
#endif
___CFUN_SET_RESULT_VOID
___END_CFUN_BODY_CLEANUP
___END_CFUN_SCMOBJ_TO_CHARSTRING(___ARG1,___arg1,1)
___END_CFUN_ARG(1)
#undef ___ARG1
___CFUN_ERROR_CLEANUP_VOID
___END_CFUN_VOID
#undef ___NARGS
   ___JUMPPRM(___NOTHING,___R0)
___DEF_SLBL(1,___L1__20_main_23_0)
   ___ADJFP(-8)
   ___JUMPPRM(___NOTHING,___STK(2))
___END_P_SW
___END_P_COD

#undef ___PH_PROC
#define ___PH_PROC ___H__2a_repl_2d_intercept_2d_output_2a_
#undef ___PH_LBL0
#define ___PH_LBL0 9
#undef ___PD_ALL
#define ___PD_ALL ___D_FP ___D_R0 ___D_R1 ___D_R4
#undef ___PR_ALL
#define ___PR_ALL ___R_FP ___R_R0 ___R_R1 ___R_R4
#undef ___PW_ALL
#define ___PW_ALL ___W_R1 ___W_R4
___BEGIN_P_COD
___BEGIN_P_HLBL
___DEF_P_HLBL_INTRO
___DEF_P_HLBL(___L0__2a_repl_2d_intercept_2d_output_2a_)
___DEF_P_HLBL(___L1__2a_repl_2d_intercept_2d_output_2a_)
___END_P_HLBL
___BEGIN_P_SW
___DEF_SLBL(0,___L0__2a_repl_2d_intercept_2d_output_2a_)
   ___IF_NARGS_EQ(1,___NOTHING)
   ___WRONG_NARGS(0,1,0,0)
___DEF_GLBL(___L__2a_repl_2d_intercept_2d_output_2a_)
   ___IF(___EQP(___GLO_void,___PRM_void))
   ___GOTO(___L2__2a_repl_2d_intercept_2d_output_2a_)
   ___END_IF
   ___POLL(1)
___DEF_SLBL(1,___L1__2a_repl_2d_intercept_2d_output_2a_)
   ___JUMPGLOSAFE(___SET_NARGS(0),50,___G_void)
___DEF_GLBL(___L2__2a_repl_2d_intercept_2d_output_2a_)
   ___SET_R1(___VOID)
   ___JUMPPRM(___NOTHING,___R0)
___END_P_SW
___END_P_COD

#undef ___PH_PROC
#define ___PH_PROC ___H_ide_2d_repl_2d_pump
#undef ___PH_LBL0
#define ___PH_LBL0 12
#undef ___PD_ALL
#define ___PD_ALL ___D_HEAP ___D_FP ___D_R0 ___D_R1 ___D_R2 ___D_R3 ___D_R4
#undef ___PR_ALL
#define ___PR_ALL ___R_HEAP ___R_FP ___R_R0 ___R_R1 ___R_R2 ___R_R3 ___R_R4
#undef ___PW_ALL
#define ___PW_ALL ___W_HEAP ___W_FP ___W_R0 ___W_R1 ___W_R2 ___W_R3 ___W_R4
___BEGIN_P_COD
___BEGIN_P_HLBL
___DEF_P_HLBL_INTRO
___DEF_P_HLBL(___L0_ide_2d_repl_2d_pump)
___DEF_P_HLBL(___L1_ide_2d_repl_2d_pump)
___DEF_P_HLBL(___L2_ide_2d_repl_2d_pump)
___DEF_P_HLBL(___L3_ide_2d_repl_2d_pump)
___DEF_P_HLBL(___L4_ide_2d_repl_2d_pump)
___DEF_P_HLBL(___L5_ide_2d_repl_2d_pump)
___DEF_P_HLBL(___L6_ide_2d_repl_2d_pump)
___DEF_P_HLBL(___L7_ide_2d_repl_2d_pump)
___DEF_P_HLBL(___L8_ide_2d_repl_2d_pump)
___DEF_P_HLBL(___L9_ide_2d_repl_2d_pump)
___DEF_P_HLBL(___L10_ide_2d_repl_2d_pump)
___DEF_P_HLBL(___L11_ide_2d_repl_2d_pump)
___DEF_P_HLBL(___L12_ide_2d_repl_2d_pump)
___DEF_P_HLBL(___L13_ide_2d_repl_2d_pump)
___DEF_P_HLBL(___L14_ide_2d_repl_2d_pump)
___DEF_P_HLBL(___L15_ide_2d_repl_2d_pump)
___DEF_P_HLBL(___L16_ide_2d_repl_2d_pump)
___DEF_P_HLBL(___L17_ide_2d_repl_2d_pump)
___DEF_P_HLBL(___L18_ide_2d_repl_2d_pump)
___DEF_P_HLBL(___L19_ide_2d_repl_2d_pump)
___DEF_P_HLBL(___L20_ide_2d_repl_2d_pump)
___DEF_P_HLBL(___L21_ide_2d_repl_2d_pump)
___DEF_P_HLBL(___L22_ide_2d_repl_2d_pump)
___DEF_P_HLBL(___L23_ide_2d_repl_2d_pump)
___DEF_P_HLBL(___L24_ide_2d_repl_2d_pump)
___DEF_P_HLBL(___L25_ide_2d_repl_2d_pump)
___DEF_P_HLBL(___L26_ide_2d_repl_2d_pump)
___DEF_P_HLBL(___L27_ide_2d_repl_2d_pump)
___DEF_P_HLBL(___L28_ide_2d_repl_2d_pump)
___DEF_P_HLBL(___L29_ide_2d_repl_2d_pump)
___DEF_P_HLBL(___L30_ide_2d_repl_2d_pump)
___DEF_P_HLBL(___L31_ide_2d_repl_2d_pump)
___DEF_P_HLBL(___L32_ide_2d_repl_2d_pump)
___DEF_P_HLBL(___L33_ide_2d_repl_2d_pump)
___DEF_P_HLBL(___L34_ide_2d_repl_2d_pump)
___DEF_P_HLBL(___L35_ide_2d_repl_2d_pump)
___DEF_P_HLBL(___L36_ide_2d_repl_2d_pump)
___DEF_P_HLBL(___L37_ide_2d_repl_2d_pump)
___DEF_P_HLBL(___L38_ide_2d_repl_2d_pump)
___DEF_P_HLBL(___L39_ide_2d_repl_2d_pump)
___DEF_P_HLBL(___L40_ide_2d_repl_2d_pump)
___DEF_P_HLBL(___L41_ide_2d_repl_2d_pump)
___DEF_P_HLBL(___L42_ide_2d_repl_2d_pump)
___DEF_P_HLBL(___L43_ide_2d_repl_2d_pump)
___DEF_P_HLBL(___L44_ide_2d_repl_2d_pump)
___DEF_P_HLBL(___L45_ide_2d_repl_2d_pump)
___DEF_P_HLBL(___L46_ide_2d_repl_2d_pump)
___DEF_P_HLBL(___L47_ide_2d_repl_2d_pump)
___DEF_P_HLBL(___L48_ide_2d_repl_2d_pump)
___DEF_P_HLBL(___L49_ide_2d_repl_2d_pump)
___DEF_P_HLBL(___L50_ide_2d_repl_2d_pump)
___DEF_P_HLBL(___L51_ide_2d_repl_2d_pump)
___DEF_P_HLBL(___L52_ide_2d_repl_2d_pump)
___DEF_P_HLBL(___L53_ide_2d_repl_2d_pump)
___DEF_P_HLBL(___L54_ide_2d_repl_2d_pump)
___DEF_P_HLBL(___L55_ide_2d_repl_2d_pump)
___DEF_P_HLBL(___L56_ide_2d_repl_2d_pump)
___DEF_P_HLBL(___L57_ide_2d_repl_2d_pump)
___DEF_P_HLBL(___L58_ide_2d_repl_2d_pump)
___DEF_P_HLBL(___L59_ide_2d_repl_2d_pump)
___END_P_HLBL
___BEGIN_P_SW
___DEF_SLBL(0,___L0_ide_2d_repl_2d_pump)
   ___IF_NARGS_EQ(4,___NOTHING)
   ___WRONG_NARGS(0,4,0,0)
___DEF_GLBL(___L_ide_2d_repl_2d_pump)
   ___SET_STK(1,___R0)
   ___SET_STK(2,___R1)
   ___SET_STK(3,___R2)
   ___SET_STK(4,___R3)
   ___SET_R0(___LBL(2))
   ___ADJFP(7)
   ___POLL(1)
___DEF_SLBL(1,___L1_ide_2d_repl_2d_pump)
   ___JUMPGLOSAFE(___SET_NARGS(0),30,___G_make_2d_mutex)
___DEF_SLBL(2,___L2_ide_2d_repl_2d_pump)
   ___SET_STK(-2,___ALLOC_CLO(4))
   ___SET_STK(-1,___ALLOC_CLO(3))
   ___BEGIN_SETUP_CLO(4,___STK(-2),27)
   ___ADD_CLO_ELEM(0,___STK(-7))
   ___ADD_CLO_ELEM(1,___R1)
   ___ADD_CLO_ELEM(2,___STK(-4))
   ___ADD_CLO_ELEM(3,___STK(-3))
   ___END_SETUP_CLO(4)
   ___BEGIN_SETUP_CLO(3,___STK(-1),14)
   ___ADD_CLO_ELEM(0,___STK(-7))
   ___ADD_CLO_ELEM(1,___STK(-5))
   ___ADD_CLO_ELEM(2,___R1)
   ___END_SETUP_CLO(3)
   ___SET_R2(___FAL)
   ___SET_R1(___SYM_repl_2d_pump)
   ___SET_R0(___LBL(4))
   ___ADJFP(4)
   ___CHECK_HEAP(3,4096)
___DEF_SLBL(3,___L3_ide_2d_repl_2d_pump)
   ___JUMPGLOSAFE(___SET_NARGS(2),33,___G_make_2d_thread_2d_group)
___DEF_SLBL(4,___L4_ide_2d_repl_2d_pump)
   ___SET_STK(-11,___R1)
   ___SET_R2(___STK(-6))
   ___SET_R0(___LBL(5))
   ___GOTO(___L60_ide_2d_repl_2d_pump)
___DEF_SLBL(5,___L5_ide_2d_repl_2d_pump)
   ___SET_R2(___STK(-5))
   ___SET_R1(___STK(-11))
   ___SET_R0(___STK(-10))
   ___ADJFP(-12)
   ___POLL(6)
___DEF_SLBL(6,___L6_ide_2d_repl_2d_pump)
___DEF_GLBL(___L60_ide_2d_repl_2d_pump)
   ___SET_STK(1,___R0)
   ___SET_STK(2,___ALLOC_CLO(1))
   ___BEGIN_SETUP_CLO(1,___STK(2),11)
   ___ADD_CLO_ELEM(0,___R2)
   ___END_SETUP_CLO(1)
   ___SET_STK(3,___R1)
   ___SET_R1(___STK(2))
   ___SET_R3(___STK(3))
   ___SET_R2(___FAL)
   ___SET_R0(___LBL(9))
   ___ADJFP(4)
   ___CHECK_HEAP(7,4096)
___DEF_SLBL(7,___L7_ide_2d_repl_2d_pump)
   ___POLL(8)
___DEF_SLBL(8,___L8_ide_2d_repl_2d_pump)
   ___JUMPGLOSAFE(___SET_NARGS(3),32,___G_make_2d_thread)
___DEF_SLBL(9,___L9_ide_2d_repl_2d_pump)
   ___SET_R0(___STK(-3))
   ___POLL(10)
___DEF_SLBL(10,___L10_ide_2d_repl_2d_pump)
   ___ADJFP(-4)
   ___JUMPGLOSAFE(___SET_NARGS(1),47,___G_thread_2d_start_21_)
___DEF_SLBL(11,___L11_ide_2d_repl_2d_pump)
   ___IF_NARGS_EQ(0,___NOTHING)
   ___WRONG_NARGS(11,0,0,0)
   ___SET_R1(___LBL(13))
   ___SET_R2(___CLO(___R4,1))
   ___POLL(12)
___DEF_SLBL(12,___L12_ide_2d_repl_2d_pump)
   ___JUMPGLOSAFE(___SET_NARGS(2),51,___G_with_2d_exception_2d_catcher)
___DEF_SLBL(13,___L13_ide_2d_repl_2d_pump)
   ___IF_NARGS_EQ(1,___NOTHING)
   ___WRONG_NARGS(13,1,0,0)
   ___SET_R1(___FAL)
   ___JUMPPRM(___NOTHING,___R0)
___DEF_SLBL(14,___L14_ide_2d_repl_2d_pump)
   ___IF_NARGS_EQ(0,___NOTHING)
   ___WRONG_NARGS(14,0,0,0)
   ___SET_R3(___CLO(___R4,3))
   ___SET_R2(___CLO(___R4,2))
   ___SET_R1(___CLO(___R4,1))
   ___POLL(15)
___DEF_SLBL(15,___L15_ide_2d_repl_2d_pump)
   ___GOTO(___L61_ide_2d_repl_2d_pump)
___DEF_SLBL(16,___L16_ide_2d_repl_2d_pump)
   ___SET_R3(___STK(-4))
   ___SET_R2(___STK(-5))
   ___SET_R1(___STK(-6))
   ___SET_R0(___STK(-7))
   ___ADJFP(-8)
   ___POLL(17)
___DEF_SLBL(17,___L17_ide_2d_repl_2d_pump)
___DEF_GLBL(___L61_ide_2d_repl_2d_pump)
   ___SET_STK(1,___R0)
   ___SET_STK(2,___R1)
   ___SET_STK(3,___R2)
   ___SET_STK(4,___R3)
   ___SET_R1(___R2)
   ___SET_R0(___LBL(19))
   ___ADJFP(8)
   ___POLL(18)
___DEF_SLBL(18,___L18_ide_2d_repl_2d_pump)
   ___JUMPGLOSAFE(___SET_NARGS(1),40,___G_read_2d_char)
___DEF_SLBL(19,___L19_ide_2d_repl_2d_pump)
   ___IF(___NOT(___EQP(___GLO_eof_2d_object_3f_,___PRM_eof_2d_object_3f_)))
   ___GOTO(___L66_ide_2d_repl_2d_pump)
   ___END_IF
   ___SET_R2(___BOOLEAN(___EOFP(___R1)))
   ___IF(___EQP(___GLO_not,___PRM_not))
   ___GOTO(___L62_ide_2d_repl_2d_pump)
   ___END_IF
   ___GOTO(___L65_ide_2d_repl_2d_pump)
___DEF_SLBL(20,___L20_ide_2d_repl_2d_pump)
   ___SET_R2(___R1)
   ___SET_R1(___STK(-3))
   ___IF(___NOT(___EQP(___GLO_not,___PRM_not)))
   ___GOTO(___L65_ide_2d_repl_2d_pump)
   ___END_IF
___DEF_GLBL(___L62_ide_2d_repl_2d_pump)
   ___IF(___FALSEP(___R2))
   ___GOTO(___L64_ide_2d_repl_2d_pump)
   ___END_IF
___DEF_GLBL(___L63_ide_2d_repl_2d_pump)
   ___SET_R1(___VOID)
   ___POLL(21)
___DEF_SLBL(21,___L21_ide_2d_repl_2d_pump)
   ___ADJFP(-8)
   ___JUMPPRM(___NOTHING,___STK(1))
___DEF_SLBL(22,___L22_ide_2d_repl_2d_pump)
   ___IF(___FALSEP(___R1))
   ___GOTO(___L63_ide_2d_repl_2d_pump)
   ___END_IF
   ___SET_R1(___STK(-3))
___DEF_GLBL(___L64_ide_2d_repl_2d_pump)
   ___SET_STK(-3,___R1)
   ___SET_R0(___LBL(23))
   ___JUMPGLOSAFE(___SET_NARGS(1),3,___G__2a_repl_2d_intercept_2d_output_2a_)
___DEF_SLBL(23,___L23_ide_2d_repl_2d_pump)
   ___SET_R1(___STK(-4))
   ___SET_R0(___LBL(24))
   ___JUMPGLOSAFE(___SET_NARGS(1),34,___G_mutex_2d_lock_21_)
___DEF_SLBL(24,___L24_ide_2d_repl_2d_pump)
   ___SET_R2(___STK(-6))
   ___SET_R1(___STK(-3))
   ___SET_R0(___LBL(25))
   ___JUMPGLOSAFE(___SET_NARGS(2),52,___G_write_2d_char)
___DEF_SLBL(25,___L25_ide_2d_repl_2d_pump)
   ___SET_R1(___STK(-6))
   ___SET_R0(___LBL(26))
   ___JUMPGLOSAFE(___SET_NARGS(1),28,___G_force_2d_output)
___DEF_SLBL(26,___L26_ide_2d_repl_2d_pump)
   ___SET_R1(___STK(-4))
   ___SET_R0(___LBL(16))
   ___JUMPGLOSAFE(___SET_NARGS(1),35,___G_mutex_2d_unlock_21_)
___DEF_GLBL(___L65_ide_2d_repl_2d_pump)
   ___SET_STK(-3,___R1)
   ___SET_R1(___R2)
   ___SET_R0(___LBL(22))
   ___JUMPGLOSAFE(___SET_NARGS(1),36,___G_not)
___DEF_GLBL(___L66_ide_2d_repl_2d_pump)
   ___SET_STK(-3,___R1)
   ___SET_R0(___LBL(20))
   ___JUMPGLOSAFE(___SET_NARGS(1),24,___G_eof_2d_object_3f_)
___DEF_SLBL(27,___L27_ide_2d_repl_2d_pump)
   ___IF_NARGS_EQ(0,___NOTHING)
   ___WRONG_NARGS(27,0,0,0)
   ___SET_STK(1,___CLO(___R4,1))
   ___SET_STK(2,___CLO(___R4,3))
   ___SET_R2(___CLO(___R4,2))
   ___SET_R1(___CLO(___R4,4))
   ___SET_R3(___SYM_normal)
   ___ADJFP(2)
   ___POLL(28)
___DEF_SLBL(28,___L28_ide_2d_repl_2d_pump)
   ___GOTO(___L67_ide_2d_repl_2d_pump)
___DEF_SLBL(29,___L29_ide_2d_repl_2d_pump)
   ___SET_R3(___STK(-6))
   ___SET_R2(___STK(-7))
   ___SET_R1(___STK(-8))
   ___SET_R0(___STK(-9))
   ___ADJFP(-10)
   ___POLL(30)
___DEF_SLBL(30,___L30_ide_2d_repl_2d_pump)
___DEF_GLBL(___L67_ide_2d_repl_2d_pump)
   ___SET_STK(1,___R0)
   ___SET_STK(2,___R1)
   ___SET_STK(3,___R2)
   ___SET_STK(4,___R3)
   ___SET_R1(___STK(-1))
   ___SET_R0(___LBL(32))
   ___ADJFP(10)
   ___POLL(31)
___DEF_SLBL(31,___L31_ide_2d_repl_2d_pump)
   ___JUMPGLOSAFE(___SET_NARGS(1),40,___G_read_2d_char)
___DEF_SLBL(32,___L32_ide_2d_repl_2d_pump)
   ___IF(___NOT(___EQP(___GLO_eof_2d_object_3f_,___PRM_eof_2d_object_3f_)))
   ___GOTO(___L94_ide_2d_repl_2d_pump)
   ___END_IF
   ___SET_R2(___BOOLEAN(___EOFP(___R1)))
   ___IF(___EQP(___GLO_not,___PRM_not))
   ___GOTO(___L68_ide_2d_repl_2d_pump)
   ___END_IF
   ___GOTO(___L93_ide_2d_repl_2d_pump)
___DEF_SLBL(33,___L33_ide_2d_repl_2d_pump)
   ___SET_R2(___R1)
   ___SET_R1(___STK(-5))
   ___IF(___NOT(___EQP(___GLO_not,___PRM_not)))
   ___GOTO(___L93_ide_2d_repl_2d_pump)
   ___END_IF
___DEF_GLBL(___L68_ide_2d_repl_2d_pump)
   ___IF(___NOT(___FALSEP(___R2)))
   ___GOTO(___L92_ide_2d_repl_2d_pump)
   ___END_IF
   ___BEGIN_SWITCH_CHAR(___STK(-6))
   ___SWITCH_CHAR_CASE_GOTO(___CHR(251),___L69_ide_2d_repl_2d_pump)
   ___SWITCH_CHAR_CASE_GOTO(___CHR(252),___L69_ide_2d_repl_2d_pump)
   ___SWITCH_CHAR_CASE_GOTO(___CHR(253),___L86_ide_2d_repl_2d_pump)
   ___SWITCH_CHAR_CASE_GOTO(___CHR(254),___L69_ide_2d_repl_2d_pump)
   ___SWITCH_CHAR_CASE_GOTO(___CHR(255),___L70_ide_2d_repl_2d_pump)
   ___END_SWITCH_CHAR
   ___IF_GOTO(___EQP(___STK(-6),___SYM_normal),___L73_ide_2d_repl_2d_pump)
___DEF_GLBL(___L69_ide_2d_repl_2d_pump)
   ___SET_R2(___STK(-7))
   ___SET_R1(___STK(-8))
   ___SET_R3(___SYM_normal)
   ___SET_R0(___STK(-9))
   ___ADJFP(-10)
   ___POLL(34)
___DEF_SLBL(34,___L34_ide_2d_repl_2d_pump)
   ___GOTO(___L67_ide_2d_repl_2d_pump)
___DEF_SLBL(35,___L35_ide_2d_repl_2d_pump)
   ___IF(___FALSEP(___R1))
   ___GOTO(___L92_ide_2d_repl_2d_pump)
   ___END_IF
   ___SET_R1(___STK(-5))
   ___BEGIN_SWITCH_CHAR(___STK(-6))
   ___SWITCH_CHAR_CASE_GOTO(___CHR(251),___L69_ide_2d_repl_2d_pump)
   ___SWITCH_CHAR_CASE_GOTO(___CHR(252),___L69_ide_2d_repl_2d_pump)
   ___SWITCH_CHAR_CASE_GOTO(___CHR(253),___L86_ide_2d_repl_2d_pump)
   ___SWITCH_CHAR_CASE_GOTO(___CHR(254),___L69_ide_2d_repl_2d_pump)
   ___SWITCH_CHAR_CASE_GOTO(___CHR(255),___L70_ide_2d_repl_2d_pump)
   ___END_SWITCH_CHAR
   ___IF_GOTO(___EQP(___STK(-6),___SYM_normal),___L73_ide_2d_repl_2d_pump)
   ___GOTO(___L69_ide_2d_repl_2d_pump)
___DEF_GLBL(___L70_ide_2d_repl_2d_pump)
   ___BEGIN_SWITCH_CHAR(___R1)
   ___SWITCH_CHAR_CASE_GOTO(___CHR(244),___L79_ide_2d_repl_2d_pump)
   ___SWITCH_CHAR_CASE_GOTO(___CHR(251),___L71_ide_2d_repl_2d_pump)
   ___SWITCH_CHAR_CASE_GOTO(___CHR(252),___L71_ide_2d_repl_2d_pump)
   ___SWITCH_CHAR_CASE_GOTO(___CHR(253),___L71_ide_2d_repl_2d_pump)
   ___SWITCH_CHAR_CASE_GOTO(___CHR(254),___L71_ide_2d_repl_2d_pump)
   ___END_SWITCH_CHAR
   ___SET_R2(___STK(-7))
   ___SET_R1(___STK(-8))
   ___SET_R3(___SYM_normal)
   ___SET_R0(___STK(-9))
   ___ADJFP(-10)
   ___POLL(36)
___DEF_SLBL(36,___L36_ide_2d_repl_2d_pump)
   ___GOTO(___L67_ide_2d_repl_2d_pump)
___DEF_SLBL(37,___L37_ide_2d_repl_2d_pump)
   ___IF(___FALSEP(___R1))
   ___GOTO(___L72_ide_2d_repl_2d_pump)
   ___END_IF
   ___SET_R1(___STK(-5))
___DEF_GLBL(___L71_ide_2d_repl_2d_pump)
   ___SET_R3(___R1)
   ___SET_R2(___STK(-7))
   ___SET_R1(___STK(-8))
   ___SET_R0(___STK(-9))
   ___ADJFP(-10)
   ___POLL(38)
___DEF_SLBL(38,___L38_ide_2d_repl_2d_pump)
   ___GOTO(___L67_ide_2d_repl_2d_pump)
___DEF_GLBL(___L72_ide_2d_repl_2d_pump)
   ___SET_R1(___STK(-5))
   ___GOTO(___L74_ide_2d_repl_2d_pump)
___DEF_GLBL(___L73_ide_2d_repl_2d_pump)
   ___IF(___NOT(___EQP(___GLO_char_3d__3f_,___PRM_char_3d__3f_)))
   ___GOTO(___L78_ide_2d_repl_2d_pump)
   ___END_IF
   ___IF(___NOT(___CHARP(___R1)))
   ___GOTO(___L78_ide_2d_repl_2d_pump)
   ___END_IF
   ___IF(___CHAREQP(___R1,___CHR(255)))
   ___GOTO(___L71_ide_2d_repl_2d_pump)
   ___END_IF
___DEF_GLBL(___L74_ide_2d_repl_2d_pump)
   ___SET_STK(-5,___R1)
   ___SET_R1(___STK(-7))
   ___SET_R0(___LBL(39))
   ___JUMPGLOSAFE(___SET_NARGS(1),34,___G_mutex_2d_lock_21_)
___DEF_SLBL(39,___L39_ide_2d_repl_2d_pump)
   ___IF(___NOT(___EQP(___GLO_char_3d__3f_,___PRM_char_3d__3f_)))
   ___GOTO(___L77_ide_2d_repl_2d_pump)
   ___END_IF
   ___IF(___NOT(___CHARP(___STK(-5))))
   ___GOTO(___L77_ide_2d_repl_2d_pump)
   ___END_IF
   ___IF(___CHAREQP(___STK(-5),___CHR(4)))
   ___GOTO(___L75_ide_2d_repl_2d_pump)
   ___END_IF
   ___GOTO(___L76_ide_2d_repl_2d_pump)
___DEF_SLBL(40,___L40_ide_2d_repl_2d_pump)
   ___IF(___FALSEP(___R1))
   ___GOTO(___L76_ide_2d_repl_2d_pump)
   ___END_IF
___DEF_GLBL(___L75_ide_2d_repl_2d_pump)
   ___SET_R1(___STK(-10))
   ___SET_R0(___LBL(41))
   ___JUMPGLOSAFE(___SET_NARGS(1),22,___G_close_2d_output_2d_port)
___DEF_SLBL(41,___L41_ide_2d_repl_2d_pump)
   ___SET_R1(___STK(-7))
   ___SET_R0(___LBL(29))
   ___JUMPGLOSAFE(___SET_NARGS(1),35,___G_mutex_2d_unlock_21_)
___DEF_GLBL(___L76_ide_2d_repl_2d_pump)
   ___SET_R2(___STK(-10))
   ___SET_R1(___STK(-5))
   ___SET_R0(___LBL(42))
   ___JUMPGLOSAFE(___SET_NARGS(2),52,___G_write_2d_char)
___DEF_SLBL(42,___L42_ide_2d_repl_2d_pump)
   ___SET_R1(___STK(-10))
   ___SET_R0(___LBL(41))
   ___JUMPGLOSAFE(___SET_NARGS(1),28,___G_force_2d_output)
___DEF_GLBL(___L77_ide_2d_repl_2d_pump)
   ___SET_R1(___STK(-5))
   ___SET_R2(___CHR(4))
   ___SET_R0(___LBL(40))
   ___JUMPGLOSAFE(___SET_NARGS(2),21,___G_char_3d__3f_)
___DEF_GLBL(___L78_ide_2d_repl_2d_pump)
   ___SET_STK(-5,___R1)
   ___SET_R2(___CHR(255))
   ___SET_R0(___LBL(37))
   ___JUMPGLOSAFE(___SET_NARGS(2),21,___G_char_3d__3f_)
___DEF_GLBL(___L79_ide_2d_repl_2d_pump)
   ___SET_STK(-6,___GLO__23__23_thread_2d_interrupt_21_)
   ___SET_R1(___STK(-8))
   ___SET_R0(___LBL(43))
   ___JUMPGLOSAFE(___SET_NARGS(1),45,___G_thread_2d_group_2d__3e_thread_2d_list)
___DEF_SLBL(43,___L43_ide_2d_repl_2d_pump)
   ___IF(___NOT(___EQP(___GLO_for_2d_each,___PRM_for_2d_each)))
   ___GOTO(___L91_ide_2d_repl_2d_pump)
   ___END_IF
   ___IF(___NOT(___PROCEDUREP(___STK(-6))))
   ___GOTO(___L91_ide_2d_repl_2d_pump)
   ___END_IF
   ___SET_R2(___STK(-6))
   ___SET_R3(___R1)
   ___SET_R0(___LBL(51))
   ___ADJFP(-4)
   ___IF(___PAIRP(___R3))
   ___GOTO(___L81_ide_2d_repl_2d_pump)
   ___END_IF
   ___GOTO(___L82_ide_2d_repl_2d_pump)
___DEF_GLBL(___L80_ide_2d_repl_2d_pump)
   ___IF(___NOT(___PAIRP(___R3)))
   ___GOTO(___L82_ide_2d_repl_2d_pump)
   ___END_IF
___DEF_GLBL(___L81_ide_2d_repl_2d_pump)
   ___SET_R3(___CDR(___R3))
   ___POLL(44)
___DEF_SLBL(44,___L44_ide_2d_repl_2d_pump)
   ___GOTO(___L80_ide_2d_repl_2d_pump)
___DEF_GLBL(___L82_ide_2d_repl_2d_pump)
   ___IF(___NOT(___NULLP(___R3)))
   ___GOTO(___L85_ide_2d_repl_2d_pump)
   ___END_IF
   ___SET_STK(1,___R2)
   ___SET_R2(___R1)
   ___SET_R1(___STK(1))
   ___POLL(45)
___DEF_SLBL(45,___L45_ide_2d_repl_2d_pump)
   ___GOTO(___L83_ide_2d_repl_2d_pump)
___DEF_SLBL(46,___L46_ide_2d_repl_2d_pump)
   ___SET_R2(___CDR(___STK(-5)))
   ___SET_R1(___STK(-6))
   ___SET_R0(___STK(-7))
   ___ADJFP(-8)
   ___POLL(47)
___DEF_SLBL(47,___L47_ide_2d_repl_2d_pump)
___DEF_GLBL(___L83_ide_2d_repl_2d_pump)
   ___IF(___NOT(___PAIRP(___R2)))
   ___GOTO(___L84_ide_2d_repl_2d_pump)
   ___END_IF
   ___SET_STK(1,___R0)
   ___SET_STK(2,___R1)
   ___SET_STK(3,___R2)
   ___SET_R1(___CAR(___R2))
   ___SET_R0(___LBL(49))
   ___ADJFP(8)
   ___POLL(48)
___DEF_SLBL(48,___L48_ide_2d_repl_2d_pump)
   ___JUMPGENSAFE(___SET_NARGS(1),___STK(-6))
___DEF_SLBL(49,___L49_ide_2d_repl_2d_pump)
   ___SET_R1(___CDR(___STK(-5)))
   ___IF(___NOT(___PAIRP(___R1)))
   ___GOTO(___L63_ide_2d_repl_2d_pump)
   ___END_IF
   ___SET_STK(-5,___R1)
   ___SET_R1(___CAR(___R1))
   ___SET_R0(___LBL(46))
   ___JUMPGENSAFE(___SET_NARGS(1),___STK(-6))
___DEF_GLBL(___L84_ide_2d_repl_2d_pump)
   ___SET_R1(___VOID)
   ___JUMPPRM(___NOTHING,___R0)
___DEF_GLBL(___L85_ide_2d_repl_2d_pump)
   ___SET_STK(1,___R2)
   ___SET_R2(___R1)
   ___SET_R1(___STK(1))
   ___ADJFP(1)
   ___POLL(50)
___DEF_SLBL(50,___L50_ide_2d_repl_2d_pump)
   ___ADJFP(-1)
   ___JUMPGLOSAFE(___SET_NARGS(2),27,___G_for_2d_each)
___DEF_SLBL(51,___L51_ide_2d_repl_2d_pump)
   ___GOTO(___L87_ide_2d_repl_2d_pump)
___DEF_GLBL(___L86_ide_2d_repl_2d_pump)
   ___IF(___NOT(___EQP(___GLO_char_3d__3f_,___PRM_char_3d__3f_)))
   ___GOTO(___L88_ide_2d_repl_2d_pump)
   ___END_IF
   ___IF(___NOT(___CHARP(___R1)))
   ___GOTO(___L88_ide_2d_repl_2d_pump)
   ___END_IF
   ___IF(___CHAREQP(___R1,___CHR(6)))
   ___GOTO(___L89_ide_2d_repl_2d_pump)
   ___END_IF
   ___ADJFP(-4)
___DEF_GLBL(___L87_ide_2d_repl_2d_pump)
   ___SET_R2(___STK(-3))
   ___SET_R1(___STK(-4))
   ___SET_R3(___SYM_normal)
   ___SET_R0(___STK(-5))
   ___ADJFP(-6)
   ___POLL(52)
___DEF_SLBL(52,___L52_ide_2d_repl_2d_pump)
   ___GOTO(___L67_ide_2d_repl_2d_pump)
___DEF_GLBL(___L88_ide_2d_repl_2d_pump)
   ___SET_R2(___CHR(6))
   ___SET_R0(___LBL(53))
   ___ADJFP(-4)
   ___JUMPGLOSAFE(___SET_NARGS(2),21,___G_char_3d__3f_)
___DEF_SLBL(53,___L53_ide_2d_repl_2d_pump)
   ___IF(___FALSEP(___R1))
   ___GOTO(___L87_ide_2d_repl_2d_pump)
   ___END_IF
   ___GOTO(___L90_ide_2d_repl_2d_pump)
___DEF_GLBL(___L89_ide_2d_repl_2d_pump)
   ___ADJFP(-4)
___DEF_GLBL(___L90_ide_2d_repl_2d_pump)
   ___SET_R1(___STK(-3))
   ___SET_R0(___LBL(54))
   ___JUMPGLOSAFE(___SET_NARGS(1),34,___G_mutex_2d_lock_21_)
___DEF_SLBL(54,___L54_ide_2d_repl_2d_pump)
   ___SET_R2(___STK(-7))
   ___SET_R1(___CHR(255))
   ___SET_R0(___LBL(55))
   ___JUMPGLOSAFE(___SET_NARGS(2),52,___G_write_2d_char)
___DEF_SLBL(55,___L55_ide_2d_repl_2d_pump)
   ___SET_R2(___STK(-7))
   ___SET_R1(___CHR(251))
   ___SET_R0(___LBL(56))
   ___JUMPGLOSAFE(___SET_NARGS(2),52,___G_write_2d_char)
___DEF_SLBL(56,___L56_ide_2d_repl_2d_pump)
   ___SET_R2(___STK(-7))
   ___SET_R1(___CHR(6))
   ___SET_R0(___LBL(57))
   ___JUMPGLOSAFE(___SET_NARGS(2),52,___G_write_2d_char)
___DEF_SLBL(57,___L57_ide_2d_repl_2d_pump)
   ___SET_R1(___STK(-7))
   ___SET_R0(___LBL(58))
   ___JUMPGLOSAFE(___SET_NARGS(1),28,___G_force_2d_output)
___DEF_SLBL(58,___L58_ide_2d_repl_2d_pump)
   ___SET_R1(___STK(-3))
   ___SET_R0(___LBL(51))
   ___JUMPGLOSAFE(___SET_NARGS(1),35,___G_mutex_2d_unlock_21_)
___DEF_GLBL(___L91_ide_2d_repl_2d_pump)
   ___SET_R2(___R1)
   ___SET_R1(___STK(-6))
   ___SET_R0(___LBL(51))
   ___ADJFP(-4)
   ___JUMPGLOSAFE(___SET_NARGS(2),27,___G_for_2d_each)
___DEF_GLBL(___L92_ide_2d_repl_2d_pump)
   ___SET_R1(___VOID)
   ___POLL(59)
___DEF_SLBL(59,___L59_ide_2d_repl_2d_pump)
   ___ADJFP(-12)
   ___JUMPPRM(___NOTHING,___STK(3))
___DEF_GLBL(___L93_ide_2d_repl_2d_pump)
   ___SET_STK(-5,___R1)
   ___SET_R1(___R2)
   ___SET_R0(___LBL(35))
   ___JUMPGLOSAFE(___SET_NARGS(1),36,___G_not)
___DEF_GLBL(___L94_ide_2d_repl_2d_pump)
   ___SET_STK(-5,___R1)
   ___SET_R0(___LBL(33))
   ___JUMPGLOSAFE(___SET_NARGS(1),24,___G_eof_2d_object_3f_)
___END_P_SW
___END_P_COD

#undef ___PH_PROC
#define ___PH_PROC ___H_make_2d_ide_2d_repl_2d_ports
#undef ___PH_LBL0
#define ___PH_LBL0 73
#undef ___PD_ALL
#define ___PD_ALL ___D_HEAP ___D_FP ___D_R0 ___D_R1 ___D_R2 ___D_R3 ___D_R4
#undef ___PR_ALL
#define ___PR_ALL ___R_HEAP ___R_FP ___R_R0 ___R_R1 ___R_R2 ___R_R3 ___R_R4
#undef ___PW_ALL
#define ___PW_ALL ___W_HEAP ___W_FP ___W_R0 ___W_R1 ___W_R2 ___W_R3 ___W_R4
___BEGIN_P_COD
___BEGIN_P_HLBL
___DEF_P_HLBL_INTRO
___DEF_P_HLBL(___L0_make_2d_ide_2d_repl_2d_ports)
___DEF_P_HLBL(___L1_make_2d_ide_2d_repl_2d_ports)
___DEF_P_HLBL(___L2_make_2d_ide_2d_repl_2d_ports)
___DEF_P_HLBL(___L3_make_2d_ide_2d_repl_2d_ports)
___DEF_P_HLBL(___L4_make_2d_ide_2d_repl_2d_ports)
___DEF_P_HLBL(___L5_make_2d_ide_2d_repl_2d_ports)
___DEF_P_HLBL(___L6_make_2d_ide_2d_repl_2d_ports)
___DEF_P_HLBL(___L7_make_2d_ide_2d_repl_2d_ports)
___DEF_P_HLBL(___L8_make_2d_ide_2d_repl_2d_ports)
___DEF_P_HLBL(___L9_make_2d_ide_2d_repl_2d_ports)
___DEF_P_HLBL(___L10_make_2d_ide_2d_repl_2d_ports)
___DEF_P_HLBL(___L11_make_2d_ide_2d_repl_2d_ports)
___DEF_P_HLBL(___L12_make_2d_ide_2d_repl_2d_ports)
___DEF_P_HLBL(___L13_make_2d_ide_2d_repl_2d_ports)
___DEF_P_HLBL(___L14_make_2d_ide_2d_repl_2d_ports)
___DEF_P_HLBL(___L15_make_2d_ide_2d_repl_2d_ports)
___DEF_P_HLBL(___L16_make_2d_ide_2d_repl_2d_ports)
___DEF_P_HLBL(___L17_make_2d_ide_2d_repl_2d_ports)
___DEF_P_HLBL(___L18_make_2d_ide_2d_repl_2d_ports)
___DEF_P_HLBL(___L19_make_2d_ide_2d_repl_2d_ports)
___END_P_HLBL
___BEGIN_P_SW
___DEF_SLBL(0,___L0_make_2d_ide_2d_repl_2d_ports)
   ___IF_NARGS_EQ(2,___NOTHING)
   ___WRONG_NARGS(0,2,0,0)
___DEF_GLBL(___L_make_2d_ide_2d_repl_2d_ports)
   ___SET_STK(1,___LBL(18))
   ___SET_STK(2,___ALLOC_CLO(2))
   ___BEGIN_SETUP_CLO(2,___STK(2),3)
   ___ADD_CLO_ELEM(0,___R1)
   ___ADD_CLO_ELEM(1,___R2)
   ___END_SETUP_CLO(2)
   ___SET_R2(___STK(2))
   ___SET_R1(___STK(1))
   ___ADJFP(2)
   ___CHECK_HEAP(1,4096)
___DEF_SLBL(1,___L1_make_2d_ide_2d_repl_2d_ports)
   ___POLL(2)
___DEF_SLBL(2,___L2_make_2d_ide_2d_repl_2d_ports)
   ___GOTO(___L20_make_2d_ide_2d_repl_2d_ports)
___DEF_SLBL(3,___L3_make_2d_ide_2d_repl_2d_ports)
   ___IF_NARGS_EQ(2,___NOTHING)
   ___WRONG_NARGS(3,2,0,0)
   ___SET_STK(1,___LBL(16))
   ___SET_STK(2,___ALLOC_CLO(4))
   ___BEGIN_SETUP_CLO(4,___STK(2),6)
   ___ADD_CLO_ELEM(0,___CLO(___R4,1))
   ___ADD_CLO_ELEM(1,___R1)
   ___ADD_CLO_ELEM(2,___R2)
   ___ADD_CLO_ELEM(3,___CLO(___R4,2))
   ___END_SETUP_CLO(4)
   ___SET_R2(___STK(2))
   ___SET_R1(___STK(1))
   ___ADJFP(2)
   ___CHECK_HEAP(4,4096)
___DEF_SLBL(4,___L4_make_2d_ide_2d_repl_2d_ports)
   ___POLL(5)
___DEF_SLBL(5,___L5_make_2d_ide_2d_repl_2d_ports)
___DEF_GLBL(___L20_make_2d_ide_2d_repl_2d_ports)
   ___ADJFP(-2)
   ___JUMPGLOSAFE(___SET_NARGS(2),15,___G__23__23_call_2d_with_2d_values)
___DEF_SLBL(6,___L6_make_2d_ide_2d_repl_2d_ports)
   ___IF_NARGS_EQ(2,___NOTHING)
   ___WRONG_NARGS(6,2,0,0)
   ___SET_STK(1,___R0)
   ___SET_STK(2,___R1)
   ___SET_STK(3,___R2)
   ___SET_STK(4,___R4)
   ___SET_R3(___LBL(15))
   ___SET_R1(___CLO(___R4,2))
   ___SET_R2(___FIX(4L))
   ___SET_R0(___LBL(8))
   ___ADJFP(8)
   ___POLL(7)
___DEF_SLBL(7,___L7_make_2d_ide_2d_repl_2d_ports)
   ___JUMPGLOSAFE(___SET_NARGS(3),20,___G__23__23_vector_2d_set_21_)
___DEF_SLBL(8,___L8_make_2d_ide_2d_repl_2d_ports)
   ___SET_R3(___LBL(14))
   ___SET_R1(___STK(-6))
   ___SET_R2(___FIX(4L))
   ___SET_R0(___LBL(9))
   ___JUMPGLOSAFE(___SET_NARGS(3),20,___G__23__23_vector_2d_set_21_)
___DEF_SLBL(9,___L9_make_2d_ide_2d_repl_2d_ports)
   ___SET_STK(1,___CLO(___STK(-4),1))
   ___SET_R3(___CLO(___STK(-4),4))
   ___SET_R2(___CLO(___STK(-4),3))
   ___SET_R1(___STK(-5))
   ___SET_R0(___LBL(10))
   ___ADJFP(1)
   ___JUMPGLOSAFE(___SET_NARGS(4),6,___G_ide_2d_repl_2d_pump)
___DEF_SLBL(10,___L10_make_2d_ide_2d_repl_2d_ports)
   ___IF(___NOT(___EQP(___GLO_values,___PRM_values)))
   ___GOTO(___L21_make_2d_ide_2d_repl_2d_ports)
   ___END_IF
   ___SET_R0(___CLO(___STK(-4),2))
   ___BEGIN_ALLOC_VALUES(2)
   ___ADD_VALUES_ELEM(0,___R0)
   ___ADD_VALUES_ELEM(1,___STK(-6))
   ___END_ALLOC_VALUES(2)
   ___SET_R1(___GET_VALUES(2))
   ___CHECK_HEAP(11,4096)
___DEF_SLBL(11,___L11_make_2d_ide_2d_repl_2d_ports)
   ___POLL(12)
___DEF_SLBL(12,___L12_make_2d_ide_2d_repl_2d_ports)
   ___ADJFP(-8)
   ___JUMPPRM(___NOTHING,___STK(1))
___DEF_GLBL(___L21_make_2d_ide_2d_repl_2d_ports)
   ___SET_R2(___STK(-6))
   ___SET_R1(___CLO(___STK(-4),2))
   ___SET_R0(___STK(-7))
   ___POLL(13)
___DEF_SLBL(13,___L13_make_2d_ide_2d_repl_2d_ports)
   ___ADJFP(-8)
   ___JUMPGLOSAFE(___SET_NARGS(2),49,___G_values)
___DEF_SLBL(14,___L14_make_2d_ide_2d_repl_2d_ports)
   ___IF_NARGS_EQ(1,___NOTHING)
   ___WRONG_NARGS(14,1,0,0)
   ___SET_R1(___CNS(0))
   ___JUMPPRM(___NOTHING,___R0)
___DEF_SLBL(15,___L15_make_2d_ide_2d_repl_2d_ports)
   ___IF_NARGS_EQ(1,___NOTHING)
   ___WRONG_NARGS(15,1,0,0)
   ___SET_R1(___CNS(1))
   ___JUMPPRM(___NOTHING,___R0)
___DEF_SLBL(16,___L16_make_2d_ide_2d_repl_2d_ports)
   ___IF_NARGS_EQ(0,___NOTHING)
   ___WRONG_NARGS(16,0,0,0)
   ___SET_R1(___CNS(2))
   ___POLL(17)
___DEF_SLBL(17,___L17_make_2d_ide_2d_repl_2d_ports)
   ___GOTO(___L22_make_2d_ide_2d_repl_2d_ports)
___DEF_SLBL(18,___L18_make_2d_ide_2d_repl_2d_ports)
   ___IF_NARGS_EQ(0,___NOTHING)
   ___WRONG_NARGS(18,0,0,0)
   ___SET_R1(___CNS(4))
   ___POLL(19)
___DEF_SLBL(19,___L19_make_2d_ide_2d_repl_2d_ports)
___DEF_GLBL(___L22_make_2d_ide_2d_repl_2d_ports)
   ___JUMPGLOSAFE(___SET_NARGS(1),37,___G_open_2d_string_2d_pipe)
___END_P_SW
___END_P_COD

#undef ___PH_PROC
#define ___PH_PROC ___H_setup_2d_ide_2d_repl_2d_channel
#undef ___PH_LBL0
#define ___PH_LBL0 94
#undef ___PD_ALL
#define ___PD_ALL ___D_HEAP ___D_FP ___D_R0 ___D_R1 ___D_R2 ___D_R3 ___D_R4
#undef ___PR_ALL
#define ___PR_ALL ___R_HEAP ___R_FP ___R_R0 ___R_R1 ___R_R2 ___R_R3 ___R_R4
#undef ___PW_ALL
#define ___PW_ALL ___W_HEAP ___W_FP ___W_R0 ___W_R1 ___W_R2 ___W_R3 ___W_R4
___BEGIN_P_COD
___BEGIN_P_HLBL
___DEF_P_HLBL_INTRO
___DEF_P_HLBL(___L0_setup_2d_ide_2d_repl_2d_channel)
___DEF_P_HLBL(___L1_setup_2d_ide_2d_repl_2d_channel)
___DEF_P_HLBL(___L2_setup_2d_ide_2d_repl_2d_channel)
___DEF_P_HLBL(___L3_setup_2d_ide_2d_repl_2d_channel)
___DEF_P_HLBL(___L4_setup_2d_ide_2d_repl_2d_channel)
___DEF_P_HLBL(___L5_setup_2d_ide_2d_repl_2d_channel)
___DEF_P_HLBL(___L6_setup_2d_ide_2d_repl_2d_channel)
___DEF_P_HLBL(___L7_setup_2d_ide_2d_repl_2d_channel)
___DEF_P_HLBL(___L8_setup_2d_ide_2d_repl_2d_channel)
___END_P_HLBL
___BEGIN_P_SW
___DEF_SLBL(0,___L0_setup_2d_ide_2d_repl_2d_channel)
   ___IF_NARGS_EQ(2,___NOTHING)
   ___WRONG_NARGS(0,2,0,0)
___DEF_GLBL(___L_setup_2d_ide_2d_repl_2d_channel)
   ___SET_STK(1,___ALLOC_CLO(2))
   ___BEGIN_SETUP_CLO(2,___STK(1),7)
   ___ADD_CLO_ELEM(0,___R1)
   ___ADD_CLO_ELEM(1,___R2)
   ___END_SETUP_CLO(2)
   ___SET_STK(2,___ALLOC_CLO(1))
   ___BEGIN_SETUP_CLO(1,___STK(2),3)
   ___ADD_CLO_ELEM(0,___R2)
   ___END_SETUP_CLO(1)
   ___SET_R2(___STK(2))
   ___SET_R1(___STK(1))
   ___ADJFP(2)
   ___CHECK_HEAP(1,4096)
___DEF_SLBL(1,___L1_setup_2d_ide_2d_repl_2d_channel)
   ___POLL(2)
___DEF_SLBL(2,___L2_setup_2d_ide_2d_repl_2d_channel)
   ___ADJFP(-2)
   ___JUMPGLOSAFE(___SET_NARGS(2),15,___G__23__23_call_2d_with_2d_values)
___DEF_SLBL(3,___L3_setup_2d_ide_2d_repl_2d_channel)
   ___IF_NARGS_EQ(2,___NOTHING)
   ___WRONG_NARGS(3,2,0,0)
   ___SET_STK(1,___R0)
   ___SET_STK(2,___R4)
   ___SET_R0(___LBL(5))
   ___ADJFP(8)
   ___POLL(4)
___DEF_SLBL(4,___L4_setup_2d_ide_2d_repl_2d_channel)
   ___JUMPGLOSAFE(___SET_NARGS(2),17,___G__23__23_make_2d_repl_2d_channel_2d_ports)
___DEF_SLBL(5,___L5_setup_2d_ide_2d_repl_2d_channel)
   ___SET_R3(___R1)
   ___SET_R2(___CLO(___STK(-6),1))
   ___SET_R1(___GLO_repl_2d_channel_2d_table)
   ___SET_R0(___STK(-7))
   ___POLL(6)
___DEF_SLBL(6,___L6_setup_2d_ide_2d_repl_2d_channel)
   ___ADJFP(-8)
   ___JUMPGLOSAFE(___SET_NARGS(3),44,___G_table_2d_set_21_)
___DEF_SLBL(7,___L7_setup_2d_ide_2d_repl_2d_channel)
   ___IF_NARGS_EQ(0,___NOTHING)
   ___WRONG_NARGS(7,0,0,0)
   ___SET_R2(___CLO(___R4,2))
   ___SET_R1(___CLO(___R4,1))
   ___POLL(8)
___DEF_SLBL(8,___L8_setup_2d_ide_2d_repl_2d_channel)
   ___JUMPGLOSAFE(___SET_NARGS(2),8,___G_make_2d_ide_2d_repl_2d_ports)
___END_P_SW
___END_P_COD

#undef ___PH_PROC
#define ___PH_PROC ___H_repl_2d_server
#undef ___PH_LBL0
#define ___PH_LBL0 104
#undef ___PD_ALL
#define ___PD_ALL ___D_HEAP ___D_FP ___D_R0 ___D_R1 ___D_R2 ___D_R3 ___D_R4
#undef ___PR_ALL
#define ___PR_ALL ___R_HEAP ___R_FP ___R_R0 ___R_R1 ___R_R2 ___R_R3 ___R_R4
#undef ___PW_ALL
#define ___PW_ALL ___W_HEAP ___W_FP ___W_R0 ___W_R1 ___W_R2 ___W_R3 ___W_R4
___BEGIN_P_COD
___BEGIN_P_HLBL
___DEF_P_HLBL_INTRO
___DEF_P_HLBL(___L0_repl_2d_server)
___DEF_P_HLBL(___L1_repl_2d_server)
___DEF_P_HLBL(___L2_repl_2d_server)
___DEF_P_HLBL(___L3_repl_2d_server)
___DEF_P_HLBL(___L4_repl_2d_server)
___DEF_P_HLBL(___L5_repl_2d_server)
___DEF_P_HLBL(___L6_repl_2d_server)
___DEF_P_HLBL(___L7_repl_2d_server)
___DEF_P_HLBL(___L8_repl_2d_server)
___DEF_P_HLBL(___L9_repl_2d_server)
___DEF_P_HLBL(___L10_repl_2d_server)
___DEF_P_HLBL(___L11_repl_2d_server)
___DEF_P_HLBL(___L12_repl_2d_server)
___DEF_P_HLBL(___L13_repl_2d_server)
___DEF_P_HLBL(___L14_repl_2d_server)
___DEF_P_HLBL(___L15_repl_2d_server)
___DEF_P_HLBL(___L16_repl_2d_server)
___DEF_P_HLBL(___L17_repl_2d_server)
___DEF_P_HLBL(___L18_repl_2d_server)
___DEF_P_HLBL(___L19_repl_2d_server)
___DEF_P_HLBL(___L20_repl_2d_server)
___DEF_P_HLBL(___L21_repl_2d_server)
___DEF_P_HLBL(___L22_repl_2d_server)
___DEF_P_HLBL(___L23_repl_2d_server)
___DEF_P_HLBL(___L24_repl_2d_server)
___DEF_P_HLBL(___L25_repl_2d_server)
___DEF_P_HLBL(___L26_repl_2d_server)
___DEF_P_HLBL(___L27_repl_2d_server)
___END_P_HLBL
___BEGIN_P_SW
___DEF_SLBL(0,___L0_repl_2d_server)
   ___IF_NARGS_EQ(1,___NOTHING)
   ___WRONG_NARGS(0,1,0,0)
___DEF_GLBL(___L_repl_2d_server)
   ___SET_STK(1,___R0)
   ___SET_STK(2,___R1)
   ___SET_STK(3,___GLO_repl_2d_server_2d_address)
   ___ADJFP(3)
   ___IF(___NOT(___EQP(___GLO_list,___PRM_list)))
   ___GOTO(___L40_repl_2d_server)
   ___END_IF
   ___BEGIN_ALLOC_LIST(6,___TRU)
   ___ADD_LIST_ELEM(1,___KEY_reuse_2d_address)
   ___ADD_LIST_ELEM(2,___SYM_cr_2d_lf)
   ___ADD_LIST_ELEM(3,___KEY_eol_2d_encoding)
   ___ADD_LIST_ELEM(4,___STK(0))
   ___ADD_LIST_ELEM(5,___KEY_server_2d_address)
   ___END_ALLOC_LIST(6)
   ___SET_R1(___GET_LIST(6))
   ___CHECK_HEAP(1,4096)
___DEF_SLBL(1,___L1_repl_2d_server)
   ___GOTO(___L28_repl_2d_server)
___DEF_SLBL(2,___L2_repl_2d_server)
   ___ADJFP(-5)
___DEF_GLBL(___L28_repl_2d_server)
   ___SET_R0(___LBL(4))
   ___ADJFP(5)
   ___POLL(3)
___DEF_SLBL(3,___L3_repl_2d_server)
   ___JUMPGLOSAFE(___SET_NARGS(1),38,___G_open_2d_tcp_2d_server)
___DEF_SLBL(4,___L4_repl_2d_server)
   ___SET_R2(___R1)
   ___SET_R1(___STK(-6))
   ___SET_R0(___STK(-7))
   ___ADJFP(-8)
   ___POLL(5)
___DEF_SLBL(5,___L5_repl_2d_server)
   ___GOTO(___L29_repl_2d_server)
___DEF_SLBL(6,___L6_repl_2d_server)
   ___SET_R2(___STK(-5))
   ___SET_R1(___STK(-6))
   ___SET_R0(___STK(-7))
   ___ADJFP(-8)
   ___POLL(7)
___DEF_SLBL(7,___L7_repl_2d_server)
___DEF_GLBL(___L29_repl_2d_server)
   ___SET_STK(1,___R0)
   ___SET_STK(2,___R1)
   ___SET_STK(3,___R2)
   ___SET_R1(___R2)
   ___SET_R0(___LBL(9))
   ___ADJFP(8)
   ___POLL(8)
___DEF_SLBL(8,___L8_repl_2d_server)
   ___JUMPGLOSAFE(___SET_NARGS(1),39,___G_read)
___DEF_SLBL(9,___L9_repl_2d_server)
   ___SET_STK(-4,___R1)
   ___SET_R2(___FAL)
   ___SET_R1(___SYM_repl_2d_service)
   ___SET_R0(___LBL(10))
   ___JUMPGLOSAFE(___SET_NARGS(2),33,___G_make_2d_thread_2d_group)
___DEF_SLBL(10,___L10_repl_2d_server)
   ___SET_STK(-3,___ALLOC_CLO(3))
   ___BEGIN_SETUP_CLO(3,___STK(-3),13)
   ___ADD_CLO_ELEM(0,___STK(-4))
   ___ADD_CLO_ELEM(1,___STK(-6))
   ___ADD_CLO_ELEM(2,___R1)
   ___END_SETUP_CLO(3)
   ___SET_STK(-4,___R1)
   ___SET_R1(___STK(-3))
   ___SET_R3(___STK(-4))
   ___SET_R2(___SYM_repl)
   ___SET_R0(___LBL(12))
   ___CHECK_HEAP(11,4096)
___DEF_SLBL(11,___L11_repl_2d_server)
   ___JUMPGLOSAFE(___SET_NARGS(3),32,___G_make_2d_thread)
___DEF_SLBL(12,___L12_repl_2d_server)
   ___SET_R0(___LBL(6))
   ___JUMPGLOSAFE(___SET_NARGS(1),47,___G_thread_2d_start_21_)
___DEF_SLBL(13,___L13_repl_2d_server)
   ___IF_NARGS_EQ(0,___NOTHING)
   ___WRONG_NARGS(13,0,0,0)
   ___SET_STK(1,___R0)
   ___SET_STK(2,___R4)
   ___SET_R2(___CLO(___R4,3))
   ___SET_R1(___CLO(___R4,1))
   ___SET_R0(___LBL(15))
   ___ADJFP(8)
   ___POLL(14)
___DEF_SLBL(14,___L14_repl_2d_server)
   ___JUMPGLOSAFE(___SET_NARGS(2),14,___G_setup_2d_ide_2d_repl_2d_channel)
___DEF_SLBL(15,___L15_repl_2d_server)
   ___IF(___NOT(___FALSEP(___CLO(___STK(-6),2))))
   ___GOTO(___L31_repl_2d_server)
   ___END_IF
   ___ADJFP(-4)
   ___GOTO(___L30_repl_2d_server)
___DEF_SLBL(16,___L16_repl_2d_server)
___DEF_GLBL(___L30_repl_2d_server)
   ___SET_R1(___SUB(0))
   ___SET_R0(___LBL(17))
   ___JUMPGLOSAFE(___SET_NARGS(1),4,___G_android_2d_display)
___DEF_SLBL(17,___L17_repl_2d_server)
   ___SET_R0(___STK(-3))
   ___POLL(18)
___DEF_SLBL(18,___L18_repl_2d_server)
   ___ADJFP(-4)
   ___JUMPGLOSAFE(___SET_NARGS(0),18,___G__23__23_repl_2d_debug_2d_main)
___DEF_GLBL(___L31_repl_2d_server)
   ___SET_R2(___CLO(___STK(-6),1))
   ___SET_R1(___CLO(___STK(-6),2))
   ___SET_R0(___LBL(16))
   ___ADJFP(-4)
   ___GOTO(___L33_repl_2d_server)
___DEF_SLBL(19,___L19_repl_2d_server)
   ___IF(___FALSEP(___R1))
   ___GOTO(___L37_repl_2d_server)
   ___END_IF
___DEF_GLBL(___L32_repl_2d_server)
   ___SET_R2(___STK(-5))
   ___SET_R1(___STK(-6))
   ___SET_R0(___STK(-7))
   ___ADJFP(-8)
   ___POLL(20)
___DEF_SLBL(20,___L20_repl_2d_server)
___DEF_GLBL(___L33_repl_2d_server)
   ___SET_STK(1,___R0)
   ___SET_STK(2,___R1)
   ___SET_STK(3,___R2)
   ___SET_R1(___SUB(1))
   ___SET_R0(___LBL(22))
   ___ADJFP(8)
   ___POLL(21)
___DEF_SLBL(21,___L21_repl_2d_server)
   ___JUMPGLOSAFE(___SET_NARGS(2),23,___G_display)
___DEF_SLBL(22,___L22_repl_2d_server)
   ___SET_R1(___STK(-5))
   ___SET_R0(___LBL(23))
   ___JUMPGLOSAFE(___SET_NARGS(1),28,___G_force_2d_output)
___DEF_SLBL(23,___L23_repl_2d_server)
   ___SET_R1(___STK(-5))
   ___SET_R0(___LBL(24))
   ___JUMPGLOSAFE(___SET_NARGS(1),41,___G_read_2d_line)
___DEF_SLBL(24,___L24_repl_2d_server)
   ___IF(___NOT(___EQP(___GLO_equal_3f_,___PRM_equal_3f_)))
   ___GOTO(___L38_repl_2d_server)
   ___END_IF
   ___IF(___NOT(___EQP(___R1,___STK(-6))))
   ___GOTO(___L34_repl_2d_server)
   ___END_IF
   ___SET_R1(___TRU)
   ___IF(___EQP(___GLO_not,___PRM_not))
   ___GOTO(___L36_repl_2d_server)
   ___END_IF
   ___GOTO(___L39_repl_2d_server)
___DEF_GLBL(___L34_repl_2d_server)
   ___IF(___NOT(___MEMALLOCATEDP(___R1)))
   ___GOTO(___L35_repl_2d_server)
   ___END_IF
   ___IF(___NOT(___MEMALLOCATEDP(___STK(-6))))
   ___GOTO(___L35_repl_2d_server)
   ___END_IF
   ___SET_R2(___SUBTYPE(___STK(-6)))
   ___SET_R3(___SUBTYPE(___R1))
   ___IF(___FIXEQ(___R3,___R2))
   ___GOTO(___L38_repl_2d_server)
   ___END_IF
___DEF_GLBL(___L35_repl_2d_server)
   ___SET_R1(___FAL)
   ___IF(___NOT(___EQP(___GLO_not,___PRM_not)))
   ___GOTO(___L39_repl_2d_server)
   ___END_IF
___DEF_GLBL(___L36_repl_2d_server)
   ___IF(___FALSEP(___R1))
   ___GOTO(___L32_repl_2d_server)
   ___END_IF
___DEF_GLBL(___L37_repl_2d_server)
   ___SET_R1(___VOID)
   ___POLL(25)
___DEF_SLBL(25,___L25_repl_2d_server)
   ___ADJFP(-8)
   ___JUMPPRM(___NOTHING,___STK(1))
___DEF_GLBL(___L38_repl_2d_server)
   ___SET_R2(___STK(-6))
   ___SET_R0(___LBL(26))
   ___JUMPGLOSAFE(___SET_NARGS(2),26,___G_equal_3f_)
___DEF_SLBL(26,___L26_repl_2d_server)
   ___IF(___EQP(___GLO_not,___PRM_not))
   ___GOTO(___L36_repl_2d_server)
   ___END_IF
___DEF_GLBL(___L39_repl_2d_server)
   ___SET_R0(___LBL(19))
   ___JUMPGLOSAFE(___SET_NARGS(1),36,___G_not)
___DEF_GLBL(___L40_repl_2d_server)
   ___SET_STK(6,___KEY_server_2d_address)
   ___SET_STK(7,___STK(0))
   ___SET_STK(8,___KEY_eol_2d_encoding)
   ___SET_R3(___TRU)
   ___SET_R2(___KEY_reuse_2d_address)
   ___SET_R1(___SYM_cr_2d_lf)
   ___SET_R0(___LBL(2))
   ___ADJFP(8)
   ___POLL(27)
___DEF_SLBL(27,___L27_repl_2d_server)
   ___JUMPGLOSAFE(___SET_NARGS(6),29,___G_list)
___END_P_SW
___END_P_COD

#undef ___PH_PROC
#define ___PH_PROC ___H_repl_2d_server_2d_start
#undef ___PH_LBL0
#define ___PH_LBL0 133
#undef ___PD_ALL
#define ___PD_ALL ___D_HEAP ___D_FP ___D_R0 ___D_R1 ___D_R2 ___D_R4
#undef ___PR_ALL
#define ___PR_ALL ___R_HEAP ___R_FP ___R_R0 ___R_R1 ___R_R2 ___R_R4
#undef ___PW_ALL
#define ___PW_ALL ___W_HEAP ___W_FP ___W_R0 ___W_R1 ___W_R2 ___W_R4
___BEGIN_P_COD
___BEGIN_P_HLBL
___DEF_P_HLBL_INTRO
___DEF_P_HLBL(___L0_repl_2d_server_2d_start)
___DEF_P_HLBL(___L1_repl_2d_server_2d_start)
___DEF_P_HLBL(___L2_repl_2d_server_2d_start)
___DEF_P_HLBL(___L3_repl_2d_server_2d_start)
___DEF_P_HLBL(___L4_repl_2d_server_2d_start)
___DEF_P_HLBL(___L5_repl_2d_server_2d_start)
___DEF_P_HLBL(___L6_repl_2d_server_2d_start)
___DEF_P_HLBL(___L7_repl_2d_server_2d_start)
___DEF_P_HLBL(___L8_repl_2d_server_2d_start)
___END_P_HLBL
___BEGIN_P_SW
___DEF_SLBL(0,___L0_repl_2d_server_2d_start)
   ___IF_NARGS_EQ(1,___SET_R2(___FAL))
   ___GET_KEY(0,1,0,1,___SUB(2))
___DEF_GLBL(___L_repl_2d_server_2d_start)
   ___IF(___FALSEP(___R2))
   ___GOTO(___L9_repl_2d_server_2d_start)
   ___END_IF
   ___SET_GLO(3,___G__2a_repl_2d_intercept_2d_output_2a_,___R2)
___DEF_GLBL(___L9_repl_2d_server_2d_start)
   ___SET_STK(1,___R0)
   ___SET_STK(2,___ALLOC_CLO(1))
   ___BEGIN_SETUP_CLO(1,___STK(2),7)
   ___ADD_CLO_ELEM(0,___R1)
   ___END_SETUP_CLO(1)
   ___SET_R1(___STK(2))
   ___SET_R0(___LBL(3))
   ___ADJFP(4)
   ___CHECK_HEAP(1,4096)
___DEF_SLBL(1,___L1_repl_2d_server_2d_start)
   ___POLL(2)
___DEF_SLBL(2,___L2_repl_2d_server_2d_start)
   ___JUMPGLOSAFE(___SET_NARGS(1),32,___G_make_2d_thread)
___DEF_SLBL(3,___L3_repl_2d_server_2d_start)
   ___SET_R0(___LBL(4))
   ___JUMPGLOSAFE(___SET_NARGS(1),47,___G_thread_2d_start_21_)
___DEF_SLBL(4,___L4_repl_2d_server_2d_start)
   ___IF(___NOT(___EQP(___GLO_void,___PRM_void)))
   ___GOTO(___L10_repl_2d_server_2d_start)
   ___END_IF
   ___SET_R1(___VOID)
   ___POLL(5)
___DEF_SLBL(5,___L5_repl_2d_server_2d_start)
   ___ADJFP(-4)
   ___JUMPPRM(___NOTHING,___STK(1))
___DEF_GLBL(___L10_repl_2d_server_2d_start)
   ___SET_R0(___STK(-3))
   ___POLL(6)
___DEF_SLBL(6,___L6_repl_2d_server_2d_start)
   ___ADJFP(-4)
   ___JUMPGLOSAFE(___SET_NARGS(0),50,___G_void)
___DEF_SLBL(7,___L7_repl_2d_server_2d_start)
   ___IF_NARGS_EQ(0,___NOTHING)
   ___WRONG_NARGS(7,0,0,0)
   ___SET_R1(___CLO(___R4,1))
   ___POLL(8)
___DEF_SLBL(8,___L8_repl_2d_server_2d_start)
   ___JUMPGLOSAFE(___SET_NARGS(1),10,___G_repl_2d_server)
___END_P_SW
___END_P_COD

#undef ___PH_PROC
#define ___PH_PROC ___H_repl_2d_server_2d_initialize_2d_defaults_21_
#undef ___PH_LBL0
#define ___PH_LBL0 143
#undef ___PD_ALL
#define ___PD_ALL ___D_FP ___D_R0 ___D_R1 ___D_R2 ___D_R3 ___D_R4
#undef ___PR_ALL
#define ___PR_ALL ___R_FP ___R_R0 ___R_R1 ___R_R2 ___R_R3 ___R_R4
#undef ___PW_ALL
#define ___PW_ALL ___W_FP ___W_R0 ___W_R1 ___W_R2 ___W_R3 ___W_R4
___BEGIN_P_COD
___BEGIN_P_HLBL
___DEF_P_HLBL_INTRO
___DEF_P_HLBL(___L0_repl_2d_server_2d_initialize_2d_defaults_21_)
___DEF_P_HLBL(___L1_repl_2d_server_2d_initialize_2d_defaults_21_)
___DEF_P_HLBL(___L2_repl_2d_server_2d_initialize_2d_defaults_21_)
___DEF_P_HLBL(___L3_repl_2d_server_2d_initialize_2d_defaults_21_)
___DEF_P_HLBL(___L4_repl_2d_server_2d_initialize_2d_defaults_21_)
___DEF_P_HLBL(___L5_repl_2d_server_2d_initialize_2d_defaults_21_)
___DEF_P_HLBL(___L6_repl_2d_server_2d_initialize_2d_defaults_21_)
___END_P_HLBL
___BEGIN_P_SW
___DEF_SLBL(0,___L0_repl_2d_server_2d_initialize_2d_defaults_21_)
   ___IF_NARGS_EQ(0,___NOTHING)
   ___WRONG_NARGS(0,0,0,0)
___DEF_GLBL(___L_repl_2d_server_2d_initialize_2d_defaults_21_)
   ___SET_GLO(2,___G__23__23_thread_2d_make_2d_repl_2d_channel,___LBL(1))
   ___SET_GLO(11,___G_repl_2d_server_2d_address,___SUB(3))
   ___SET_R1(___VOID)
   ___JUMPPRM(___NOTHING,___R0)
___DEF_SLBL(1,___L1_repl_2d_server_2d_initialize_2d_defaults_21_)
   ___IF_NARGS_EQ(1,___NOTHING)
   ___WRONG_NARGS(1,1,0,0)
   ___SET_STK(1,___R0)
   ___SET_STK(2,___R1)
   ___SET_R0(___LBL(3))
   ___ADJFP(8)
   ___POLL(2)
___DEF_SLBL(2,___L2_repl_2d_server_2d_initialize_2d_defaults_21_)
   ___JUMPGLOSAFE(___SET_NARGS(1),48,___G_thread_2d_thread_2d_group)
___DEF_SLBL(3,___L3_repl_2d_server_2d_initialize_2d_defaults_21_)
   ___SET_R2(___R1)
   ___SET_R3(___FAL)
   ___SET_R1(___GLO_repl_2d_channel_2d_table)
   ___SET_R0(___LBL(4))
   ___JUMPGLOSAFE(___SET_NARGS(3),43,___G_table_2d_ref)
___DEF_SLBL(4,___L4_repl_2d_server_2d_initialize_2d_defaults_21_)
   ___IF(___NOT(___FALSEP(___R1)))
   ___GOTO(___L7_repl_2d_server_2d_initialize_2d_defaults_21_)
   ___END_IF
   ___SET_R1(___STK(-6))
   ___SET_R0(___STK(-7))
   ___POLL(5)
___DEF_SLBL(5,___L5_repl_2d_server_2d_initialize_2d_defaults_21_)
   ___ADJFP(-8)
   ___JUMPGLOSAFE(___SET_NARGS(1),16,___G__23__23_default_2d_thread_2d_make_2d_repl_2d_channel)
___DEF_GLBL(___L7_repl_2d_server_2d_initialize_2d_defaults_21_)
   ___POLL(6)
___DEF_SLBL(6,___L6_repl_2d_server_2d_initialize_2d_defaults_21_)
   ___ADJFP(-8)
   ___JUMPPRM(___NOTHING,___STK(1))
___END_P_SW
___END_P_COD

#undef ___PH_PROC
#define ___PH_PROC ___H_main
#undef ___PH_LBL0
#define ___PH_LBL0 151
#undef ___PD_ALL
#define ___PD_ALL ___D_FP ___D_R0 ___D_R1 ___D_R2 ___D_R3 ___D_R4
#undef ___PR_ALL
#define ___PR_ALL ___R_FP ___R_R0 ___R_R1 ___R_R2 ___R_R3 ___R_R4
#undef ___PW_ALL
#define ___PW_ALL ___W_FP ___W_R0 ___W_R1 ___W_R2 ___W_R3 ___W_R4
___BEGIN_P_COD
___BEGIN_P_HLBL
___DEF_P_HLBL_INTRO
___DEF_P_HLBL(___L0_main)
___DEF_P_HLBL(___L1_main)
___DEF_P_HLBL(___L2_main)
___DEF_P_HLBL(___L3_main)
___DEF_P_HLBL(___L4_main)
___DEF_P_HLBL(___L5_main)
___DEF_P_HLBL(___L6_main)
___DEF_P_HLBL(___L7_main)
___DEF_P_HLBL(___L8_main)
___END_P_HLBL
___BEGIN_P_SW
___DEF_SLBL(0,___L0_main)
   ___IF_NARGS_EQ(0,___NOTHING)
   ___WRONG_NARGS(0,0,0,0)
___DEF_GLBL(___L_main)
   ___SET_STK(1,___R0)
   ___SET_R0(___LBL(2))
   ___ADJFP(4)
   ___POLL(1)
___DEF_SLBL(1,___L1_main)
   ___JUMPGLOSAFE(___SET_NARGS(0),12,___G_repl_2d_server_2d_initialize_2d_defaults_21_)
___DEF_SLBL(2,___L2_main)
   ___SET_R3(___LBL(5))
   ___SET_R2(___KEY_intercept_2d_output)
   ___SET_R1(___SUB(4))
   ___SET_R0(___LBL(3))
   ___JUMPGLOSAFE(___SET_NARGS(3),13,___G_repl_2d_server_2d_start)
___DEF_SLBL(3,___L3_main)
   ___SET_R1(___SUB(5))
   ___SET_R0(___STK(-3))
   ___POLL(4)
___DEF_SLBL(4,___L4_main)
   ___ADJFP(-4)
   ___JUMPGLOSAFE(___SET_NARGS(1),46,___G_thread_2d_sleep_21_)
___DEF_SLBL(5,___L5_main)
   ___IF_NARGS_EQ(1,___NOTHING)
   ___WRONG_NARGS(5,1,0,0)
   ___SET_STK(1,___R0)
   ___SET_R0(___LBL(7))
   ___ADJFP(4)
   ___POLL(6)
___DEF_SLBL(6,___L6_main)
   ___JUMPGLOSAFE(___SET_NARGS(1),42,___G_string)
___DEF_SLBL(7,___L7_main)
   ___SET_R0(___STK(-3))
   ___POLL(8)
___DEF_SLBL(8,___L8_main)
   ___ADJFP(-4)
   ___JUMPGLOSAFE(___SET_NARGS(1),4,___G_android_2d_display)
___END_P_SW
___END_P_COD

#undef ___PH_PROC
#define ___PH_PROC ___H_c_2d_scheme_2d_main
#undef ___PH_LBL0
#define ___PH_LBL0 161
#undef ___PD_ALL
#define ___PD_ALL ___D_FP ___D_R4
#undef ___PR_ALL
#define ___PR_ALL ___R_FP ___R_R4
#undef ___PW_ALL
#define ___PW_ALL ___W_R4
___BEGIN_P_COD
___BEGIN_P_HLBL
___DEF_P_HLBL_INTRO
___DEF_P_HLBL(___L0_c_2d_scheme_2d_main)
___DEF_P_HLBL(___L1_c_2d_scheme_2d_main)
___END_P_HLBL
___BEGIN_P_SW
___DEF_SLBL(0,___L0_c_2d_scheme_2d_main)
   ___IF_NARGS_EQ(0,___NOTHING)
   ___WRONG_NARGS(0,0,0,0)
___DEF_GLBL(___L_c_2d_scheme_2d_main)
   ___POLL(1)
___DEF_SLBL(1,___L1_c_2d_scheme_2d_main)
   ___JUMPGLOSAFE(___SET_NARGS(0),7,___G_main)
___END_P_SW
___END_P_COD

___END_M_SW
___END_M_COD

___BEGIN_LBL
 ___DEF_LBL_INTRO(___H__20_main," main",___REF_FAL,4,0)
,___DEF_LBL_PROC(___H__20_main,0,-1)
,___DEF_LBL_RET(___H__20_main,___IFD(___RETI,4,0,0x3f1L))
,___DEF_LBL_RET(___H__20_main,___IFD(___RETN,1,0,0x1L))
,___DEF_LBL_RET(___H__20_main,___IFD(___RETI,4,0,0x3f1L))
,___DEF_LBL_INTRO(___H__20_main_23_0," main#0",___REF_FAL,2,0)
,___DEF_LBL_PROC(___H__20_main_23_0,1,-1)
,___DEF_LBL_RET(___H__20_main_23_0,___IFD(___RETN,2,1,0x3L))
,___DEF_LBL_INTRO(___H__2a_repl_2d_intercept_2d_output_2a_,0,___REF_FAL,2,0)
,___DEF_LBL_PROC(___H__2a_repl_2d_intercept_2d_output_2a_,1,-1)
,___DEF_LBL_RET(___H__2a_repl_2d_intercept_2d_output_2a_,___IFD(___RETI,0,0,0x3fL))
,___DEF_LBL_INTRO(___H_ide_2d_repl_2d_pump,0,___REF_FAL,60,0)
,___DEF_LBL_PROC(___H_ide_2d_repl_2d_pump,4,-1)
,___DEF_LBL_RET(___H_ide_2d_repl_2d_pump,___IFD(___RETI,8,1,0x3f1fL))
,___DEF_LBL_RET(___H_ide_2d_repl_2d_pump,___IFD(___RETN,5,1,0x1fL))
,___DEF_LBL_RET(___H_ide_2d_repl_2d_pump,___OFD(___RETI,12,1,0x3f062L))
,___DEF_LBL_RET(___H_ide_2d_repl_2d_pump,___IFD(___RETN,9,1,0x62L))
,___DEF_LBL_RET(___H_ide_2d_repl_2d_pump,___IFD(___RETN,9,1,0x43L))
,___DEF_LBL_RET(___H_ide_2d_repl_2d_pump,___IFD(___RETI,0,0,0x3fL))
,___DEF_LBL_RET(___H_ide_2d_repl_2d_pump,___IFD(___RETI,4,0,0x3f1L))
,___DEF_LBL_RET(___H_ide_2d_repl_2d_pump,___IFD(___RETI,4,0,0x3f1L))
,___DEF_LBL_RET(___H_ide_2d_repl_2d_pump,___IFD(___RETN,1,0,0x1L))
,___DEF_LBL_RET(___H_ide_2d_repl_2d_pump,___IFD(___RETI,4,4,0x3f0L))
,___DEF_LBL_PROC(___H_ide_2d_repl_2d_pump,0,1)
,___DEF_LBL_RET(___H_ide_2d_repl_2d_pump,___IFD(___RETI,0,0,0x3fL))
,___DEF_LBL_PROC(___H_ide_2d_repl_2d_pump,1,-1)
,___DEF_LBL_PROC(___H_ide_2d_repl_2d_pump,0,3)
,___DEF_LBL_RET(___H_ide_2d_repl_2d_pump,___IFD(___RETI,0,0,0x3fL))
,___DEF_LBL_RET(___H_ide_2d_repl_2d_pump,___IFD(___RETN,5,0,0xfL))
,___DEF_LBL_RET(___H_ide_2d_repl_2d_pump,___IFD(___RETI,0,0,0x3fL))
,___DEF_LBL_RET(___H_ide_2d_repl_2d_pump,___IFD(___RETI,8,0,0x3f0fL))
,___DEF_LBL_RET(___H_ide_2d_repl_2d_pump,___IFD(___RETN,5,0,0xfL))
,___DEF_LBL_RET(___H_ide_2d_repl_2d_pump,___IFD(___RETN,5,0,0x1fL))
,___DEF_LBL_RET(___H_ide_2d_repl_2d_pump,___IFD(___RETI,8,0,0x3f01L))
,___DEF_LBL_RET(___H_ide_2d_repl_2d_pump,___IFD(___RETN,5,0,0x1fL))
,___DEF_LBL_RET(___H_ide_2d_repl_2d_pump,___IFD(___RETN,5,0,0x1fL))
,___DEF_LBL_RET(___H_ide_2d_repl_2d_pump,___IFD(___RETN,5,0,0x1fL))
,___DEF_LBL_RET(___H_ide_2d_repl_2d_pump,___IFD(___RETN,5,0,0xfL))
,___DEF_LBL_RET(___H_ide_2d_repl_2d_pump,___IFD(___RETN,5,0,0xfL))
,___DEF_LBL_PROC(___H_ide_2d_repl_2d_pump,0,4)
,___DEF_LBL_RET(___H_ide_2d_repl_2d_pump,___IFD(___RETI,2,4,0x3f3L))
,___DEF_LBL_RET(___H_ide_2d_repl_2d_pump,___IFD(___RETN,9,2,0x3fL))
,___DEF_LBL_RET(___H_ide_2d_repl_2d_pump,___IFD(___RETI,2,4,0x3f3L))
,___DEF_LBL_RET(___H_ide_2d_repl_2d_pump,___OFD(___RETI,12,2,0x3f03fL))
,___DEF_LBL_RET(___H_ide_2d_repl_2d_pump,___IFD(___RETN,9,2,0x3fL))
,___DEF_LBL_RET(___H_ide_2d_repl_2d_pump,___IFD(___RETN,9,2,0x7fL))
,___DEF_LBL_RET(___H_ide_2d_repl_2d_pump,___IFD(___RETI,2,4,0x3f3L))
,___DEF_LBL_RET(___H_ide_2d_repl_2d_pump,___IFD(___RETN,9,2,0x7fL))
,___DEF_LBL_RET(___H_ide_2d_repl_2d_pump,___IFD(___RETI,2,4,0x3f3L))
,___DEF_LBL_RET(___H_ide_2d_repl_2d_pump,___IFD(___RETN,9,2,0x7fL))
,___DEF_LBL_RET(___H_ide_2d_repl_2d_pump,___IFD(___RETI,2,4,0x3f3L))
,___DEF_LBL_RET(___H_ide_2d_repl_2d_pump,___IFD(___RETN,9,2,0x7fL))
,___DEF_LBL_RET(___H_ide_2d_repl_2d_pump,___IFD(___RETN,9,2,0x7fL))
,___DEF_LBL_RET(___H_ide_2d_repl_2d_pump,___IFD(___RETN,9,2,0x3fL))
,___DEF_LBL_RET(___H_ide_2d_repl_2d_pump,___IFD(___RETN,9,2,0x3fL))
,___DEF_LBL_RET(___H_ide_2d_repl_2d_pump,___IFD(___RETN,9,2,0x3fL))
,___DEF_LBL_RET(___H_ide_2d_repl_2d_pump,___IFD(___RETI,0,0,0x3fL))
,___DEF_LBL_RET(___H_ide_2d_repl_2d_pump,___IFD(___RETI,0,0,0x3fL))
,___DEF_LBL_RET(___H_ide_2d_repl_2d_pump,___IFD(___RETN,5,0,0x7L))
,___DEF_LBL_RET(___H_ide_2d_repl_2d_pump,___IFD(___RETI,0,0,0x3fL))
,___DEF_LBL_RET(___H_ide_2d_repl_2d_pump,___IFD(___RETI,8,0,0x3f07L))
,___DEF_LBL_RET(___H_ide_2d_repl_2d_pump,___IFD(___RETN,5,0,0x7L))
,___DEF_LBL_RET(___H_ide_2d_repl_2d_pump,___IFD(___RETI,1,4,0x3f0L))
,___DEF_LBL_RET(___H_ide_2d_repl_2d_pump,___IFD(___RETN,5,2,0x1fL))
,___DEF_LBL_RET(___H_ide_2d_repl_2d_pump,___IFD(___RETI,2,4,0x3f3L))
,___DEF_LBL_RET(___H_ide_2d_repl_2d_pump,___IFD(___RETN,5,2,0x1fL))
,___DEF_LBL_RET(___H_ide_2d_repl_2d_pump,___IFD(___RETN,5,2,0x1fL))
,___DEF_LBL_RET(___H_ide_2d_repl_2d_pump,___IFD(___RETN,5,2,0x1fL))
,___DEF_LBL_RET(___H_ide_2d_repl_2d_pump,___IFD(___RETN,5,2,0x1fL))
,___DEF_LBL_RET(___H_ide_2d_repl_2d_pump,___IFD(___RETN,5,2,0x1fL))
,___DEF_LBL_RET(___H_ide_2d_repl_2d_pump,___IFD(___RETN,5,2,0x1fL))
,___DEF_LBL_RET(___H_ide_2d_repl_2d_pump,___OFD(___RETI,12,2,0x3f004L))
,___DEF_LBL_INTRO(___H_make_2d_ide_2d_repl_2d_ports,0,___REF_FAL,20,0)
,___DEF_LBL_PROC(___H_make_2d_ide_2d_repl_2d_ports,2,-1)
,___DEF_LBL_RET(___H_make_2d_ide_2d_repl_2d_ports,___IFD(___RETI,2,4,0x3f1L))
,___DEF_LBL_RET(___H_make_2d_ide_2d_repl_2d_ports,___IFD(___RETI,2,4,0x3f1L))
,___DEF_LBL_PROC(___H_make_2d_ide_2d_repl_2d_ports,2,2)
,___DEF_LBL_RET(___H_make_2d_ide_2d_repl_2d_ports,___IFD(___RETI,2,4,0x3f1L))
,___DEF_LBL_RET(___H_make_2d_ide_2d_repl_2d_ports,___IFD(___RETI,2,4,0x3f1L))
,___DEF_LBL_PROC(___H_make_2d_ide_2d_repl_2d_ports,2,4)
,___DEF_LBL_RET(___H_make_2d_ide_2d_repl_2d_ports,___IFD(___RETI,8,0,0x3f0fL))
,___DEF_LBL_RET(___H_make_2d_ide_2d_repl_2d_ports,___IFD(___RETN,5,0,0xfL))
,___DEF_LBL_RET(___H_make_2d_ide_2d_repl_2d_ports,___IFD(___RETN,5,0,0xfL))
,___DEF_LBL_RET(___H_make_2d_ide_2d_repl_2d_ports,___IFD(___RETN,5,0,0xbL))
,___DEF_LBL_RET(___H_make_2d_ide_2d_repl_2d_ports,___IFD(___RETI,8,0,0x3f01L))
,___DEF_LBL_RET(___H_make_2d_ide_2d_repl_2d_ports,___IFD(___RETI,8,0,0x3f01L))
,___DEF_LBL_RET(___H_make_2d_ide_2d_repl_2d_ports,___IFD(___RETI,8,8,0x3f00L))
,___DEF_LBL_PROC(___H_make_2d_ide_2d_repl_2d_ports,1,-1)
,___DEF_LBL_PROC(___H_make_2d_ide_2d_repl_2d_ports,1,-1)
,___DEF_LBL_PROC(___H_make_2d_ide_2d_repl_2d_ports,0,-1)
,___DEF_LBL_RET(___H_make_2d_ide_2d_repl_2d_ports,___IFD(___RETI,0,0,0x3fL))
,___DEF_LBL_PROC(___H_make_2d_ide_2d_repl_2d_ports,0,-1)
,___DEF_LBL_RET(___H_make_2d_ide_2d_repl_2d_ports,___IFD(___RETI,0,0,0x3fL))
,___DEF_LBL_INTRO(___H_setup_2d_ide_2d_repl_2d_channel,0,___REF_FAL,9,0)
,___DEF_LBL_PROC(___H_setup_2d_ide_2d_repl_2d_channel,2,-1)
,___DEF_LBL_RET(___H_setup_2d_ide_2d_repl_2d_channel,___IFD(___RETI,2,4,0x3f1L))
,___DEF_LBL_RET(___H_setup_2d_ide_2d_repl_2d_channel,___IFD(___RETI,2,4,0x3f1L))
,___DEF_LBL_PROC(___H_setup_2d_ide_2d_repl_2d_channel,2,1)
,___DEF_LBL_RET(___H_setup_2d_ide_2d_repl_2d_channel,___IFD(___RETI,8,0,0x3f03L))
,___DEF_LBL_RET(___H_setup_2d_ide_2d_repl_2d_channel,___IFD(___RETN,5,0,0x3L))
,___DEF_LBL_RET(___H_setup_2d_ide_2d_repl_2d_channel,___IFD(___RETI,8,8,0x3f00L))
,___DEF_LBL_PROC(___H_setup_2d_ide_2d_repl_2d_channel,0,2)
,___DEF_LBL_RET(___H_setup_2d_ide_2d_repl_2d_channel,___IFD(___RETI,0,0,0x3fL))
,___DEF_LBL_INTRO(___H_repl_2d_server,0,___REF_FAL,28,0)
,___DEF_LBL_PROC(___H_repl_2d_server,1,-1)
,___DEF_LBL_RET(___H_repl_2d_server,___IFD(___RETI,3,0,0x3f3L))
,___DEF_LBL_RET(___H_repl_2d_server,___IFD(___RETN,5,0,0x3L))
,___DEF_LBL_RET(___H_repl_2d_server,___IFD(___RETI,8,0,0x3f03L))
,___DEF_LBL_RET(___H_repl_2d_server,___IFD(___RETN,5,0,0x3L))
,___DEF_LBL_RET(___H_repl_2d_server,___IFD(___RETI,0,0,0x3fL))
,___DEF_LBL_RET(___H_repl_2d_server,___IFD(___RETN,5,0,0x7L))
,___DEF_LBL_RET(___H_repl_2d_server,___IFD(___RETI,0,0,0x3fL))
,___DEF_LBL_RET(___H_repl_2d_server,___IFD(___RETI,8,0,0x3f07L))
,___DEF_LBL_RET(___H_repl_2d_server,___IFD(___RETN,5,0,0x7L))
,___DEF_LBL_RET(___H_repl_2d_server,___IFD(___RETN,5,0,0xfL))
,___DEF_LBL_RET(___H_repl_2d_server,___IFD(___RETI,8,0,0x3f07L))
,___DEF_LBL_RET(___H_repl_2d_server,___IFD(___RETN,5,0,0x7L))
,___DEF_LBL_PROC(___H_repl_2d_server,0,3)
,___DEF_LBL_RET(___H_repl_2d_server,___IFD(___RETI,8,0,0x3f03L))
,___DEF_LBL_RET(___H_repl_2d_server,___IFD(___RETN,5,0,0x3L))
,___DEF_LBL_RET(___H_repl_2d_server,___IFD(___RETN,1,0,0x1L))
,___DEF_LBL_RET(___H_repl_2d_server,___IFD(___RETN,1,0,0x1L))
,___DEF_LBL_RET(___H_repl_2d_server,___IFD(___RETI,4,4,0x3f0L))
,___DEF_LBL_RET(___H_repl_2d_server,___IFD(___RETN,5,0,0x7L))
,___DEF_LBL_RET(___H_repl_2d_server,___IFD(___RETI,0,0,0x3fL))
,___DEF_LBL_RET(___H_repl_2d_server,___IFD(___RETI,8,0,0x3f07L))
,___DEF_LBL_RET(___H_repl_2d_server,___IFD(___RETN,5,0,0x7L))
,___DEF_LBL_RET(___H_repl_2d_server,___IFD(___RETN,5,0,0x7L))
,___DEF_LBL_RET(___H_repl_2d_server,___IFD(___RETN,5,0,0x7L))
,___DEF_LBL_RET(___H_repl_2d_server,___IFD(___RETI,8,0,0x3f01L))
,___DEF_LBL_RET(___H_repl_2d_server,___IFD(___RETN,5,0,0x7L))
,___DEF_LBL_RET(___H_repl_2d_server,___OFD(___RETI,11,0,0x3f703L))
,___DEF_LBL_INTRO(___H_repl_2d_server_2d_start,0,___REF_FAL,9,0)
,___DEF_LBL_PROC(___H_repl_2d_server_2d_start,2,-1)
,___DEF_LBL_RET(___H_repl_2d_server_2d_start,___IFD(___RETI,4,0,0x3f1L))
,___DEF_LBL_RET(___H_repl_2d_server_2d_start,___IFD(___RETI,4,0,0x3f1L))
,___DEF_LBL_RET(___H_repl_2d_server_2d_start,___IFD(___RETN,1,0,0x1L))
,___DEF_LBL_RET(___H_repl_2d_server_2d_start,___IFD(___RETN,1,0,0x1L))
,___DEF_LBL_RET(___H_repl_2d_server_2d_start,___IFD(___RETI,4,0,0x3f1L))
,___DEF_LBL_RET(___H_repl_2d_server_2d_start,___IFD(___RETI,4,4,0x3f0L))
,___DEF_LBL_PROC(___H_repl_2d_server_2d_start,0,1)
,___DEF_LBL_RET(___H_repl_2d_server_2d_start,___IFD(___RETI,0,0,0x3fL))
,___DEF_LBL_INTRO(___H_repl_2d_server_2d_initialize_2d_defaults_21_,0,___REF_FAL,7,0)
,___DEF_LBL_PROC(___H_repl_2d_server_2d_initialize_2d_defaults_21_,0,-1)
,___DEF_LBL_PROC(___H_repl_2d_server_2d_initialize_2d_defaults_21_,1,-1)
,___DEF_LBL_RET(___H_repl_2d_server_2d_initialize_2d_defaults_21_,___IFD(___RETI,8,0,0x3f03L))
,___DEF_LBL_RET(___H_repl_2d_server_2d_initialize_2d_defaults_21_,___IFD(___RETN,5,0,0x3L))
,___DEF_LBL_RET(___H_repl_2d_server_2d_initialize_2d_defaults_21_,___IFD(___RETN,5,0,0x3L))
,___DEF_LBL_RET(___H_repl_2d_server_2d_initialize_2d_defaults_21_,___IFD(___RETI,8,8,0x3f00L))
,___DEF_LBL_RET(___H_repl_2d_server_2d_initialize_2d_defaults_21_,___IFD(___RETI,8,0,0x3f01L))
,___DEF_LBL_INTRO(___H_main,0,___REF_FAL,9,0)
,___DEF_LBL_PROC(___H_main,0,-1)
,___DEF_LBL_RET(___H_main,___IFD(___RETI,4,0,0x3f1L))
,___DEF_LBL_RET(___H_main,___IFD(___RETN,1,0,0x1L))
,___DEF_LBL_RET(___H_main,___IFD(___RETN,1,0,0x1L))
,___DEF_LBL_RET(___H_main,___IFD(___RETI,4,4,0x3f0L))
,___DEF_LBL_PROC(___H_main,1,-1)
,___DEF_LBL_RET(___H_main,___IFD(___RETI,4,0,0x3f1L))
,___DEF_LBL_RET(___H_main,___IFD(___RETN,1,0,0x1L))
,___DEF_LBL_RET(___H_main,___IFD(___RETI,4,4,0x3f0L))
,___DEF_LBL_INTRO(___H_c_2d_scheme_2d_main,0,___REF_FAL,2,scheme_main)
,___DEF_LBL_PROC(___H_c_2d_scheme_2d_main,0,-1)
,___DEF_LBL_RET(___H_c_2d_scheme_2d_main,___IFD(___RETI,0,0,0x3fL))
___END_LBL

___BEGIN_OFD
 ___DEF_OFD(___RETI,12,1)
               ___GCMAP1(0x3f062L)
,___DEF_OFD(___RETI,12,2)
               ___GCMAP1(0x3f03fL)
,___DEF_OFD(___RETI,12,2)
               ___GCMAP1(0x3f004L)
,___DEF_OFD(___RETI,11,0)
               ___GCMAP1(0x3f703L)
___END_OFD

___BEGIN_MOD_PRM
___DEF_MOD_PRM(0,___G__20_main,1)
___DEF_MOD_PRM(1,___G__20_main_23_0,6)
___END_MOD_PRM

___BEGIN_MOD_C_INIT
___END_MOD_C_INIT

___BEGIN_MOD_GLO
___DEF_MOD_GLO(0,___G__20_main,1)
___DEF_MOD_GLO(1,___G__20_main_23_0,6)
___END_MOD_GLO

___BEGIN_MOD_SYM_KEY
___DEF_MOD_SYM(0,___S_cr_2d_lf,"cr-lf")
___DEF_MOD_SYM(1,___S_input,"input")
___DEF_MOD_SYM(2,___S_main,"main")
___DEF_MOD_SYM(3,___S_normal,"normal")
___DEF_MOD_SYM(4,___S_output,"output")
___DEF_MOD_SYM(5,___S_repl,"repl")
___DEF_MOD_SYM(6,___S_repl_2d_pump,"repl-pump")
___DEF_MOD_SYM(7,___S_repl_2d_service,"repl-service")
___DEF_MOD_SYM(8,___S_stdin,"stdin")
___DEF_MOD_SYM(9,___S_stdout,"stdout")
___DEF_MOD_KEY(0,___K_direction,"direction")
___DEF_MOD_KEY(1,___K_eol_2d_encoding,"eol-encoding")
___DEF_MOD_KEY(2,___K_intercept_2d_output,"intercept-output")
___DEF_MOD_KEY(3,___K_permanent_2d_close,"permanent-close")
___DEF_MOD_KEY(4,___K_reuse_2d_address,"reuse-address")
___DEF_MOD_KEY(5,___K_server_2d_address,"server-address")
___DEF_MOD_KEY(6,___K_test,"test")
___END_MOD_SYM_KEY

#endif
